---
title: Swahili
---

# Background

**Language family**: Bantu language / lingua franca

Swahili is also sometimes referred to as Kiswahili

# Phonology

## Consonants

### By place of articulation:

Labial: /m/, /ᵐb/, /b/, /p/, /ᶬv/, /v/, /f/
Dental: /ð/, /θ/
Alveolar: /n/, /ⁿd/, /d/, /t/, /ⁿz/, /z/, /s/, /r/, /l/
Postalveolar/Palatal: /ɲ/, /ⁿdʒ/, /d͡ʒ/, /t͡ʃ/, /ʃ/, /j/
Velar: /ŋ/, /ᵑɡ/, /ɡ/, /k/, /ɣ/, /x/, /w/
Glottal: /h/

### By manner of articulation:

Nasal: /m/, /n/, /ɲ/, /ŋ/
Stops:
  Prenasalized: /ᵐb/, /ⁿd/, /ⁿdʒ/, /ᵑɡ/
  Voiced: /b/, /d/, /d͡ʒ/, /ɡ/
  Voiceless: /p/, /t/, /t͡ʃ/, /k/
Fricatives:
  Prenasalized: /ᶬv/, /ⁿz/
  Voiced: /v/, /ð/, /z/, /ɣ/
  Voiceless: /f/, /θ/, /s/, /ʃ/, /x/, /h/
Rhotic: /r/
Approximant: /l/, /j/, /w/


## Vowels:

Front vowels: /i/, /ɛ/
Back vowels: /u/, /ɔ/, /ɑ/

## Stress

As a rule, stress falls on the penultimate syllable of words in Swahili. However, there are cases in some loan words (mainly from Arabic and Persian), where the stress may fall on the first syllable.

# Alphabet

## Phonemic

Capital letter; lowercase letter; phoneme;

A; a; /ɑ/
B; b; /b/
Ch; ch; /t͡ʃ/
D; d; /d/
E; e; /ɛ/
F; f; /f/
G; g; /g/
H; h; /h/
I; i; /i/
J; j; /d͡ʒ/
K; k; /k/
L; l; /l/
M; m; /m/
N; n; /n/
O; o; /ɔ/
P; p; /p/
R; r; /r/
S; s; /s/
T; t; /t/
U; u; /u/
V; v; /v/
W; w; /w/
Y; y; /j/
Z; z; /z/

## Possible Syllable Structures
- CV
- CVC
- CVCC
- CCV
- CCCV
- V

# Lenition Processes

* /n/ ---> /j/ before a noun or an adjective with a vowel stem
* /lu/ --> /u/
* /l/ remains before /i/, but drops out before /u/.
* /v/ before /i/ becomes /w/ (/vi/ --> /w/), and before /u/ it drops out (/vu/ --> /v/)
