---
title: "Amele"
author: "Bill Mizgerd"
bibliography: aey.bib
output: html_document
---

Last Updated: 2019-09-23

# Background

**Language Family**: Trans-New Guinea / Madang / Croisilles / Mabuso / Gum / Amele

# Phonology

## Consonants

* The Huar dialect includes /r/, which does not exist in any other dialects of Amele. [@AeyRoberts2016, p. 81]

### By place of articulation

Labial: /b/, /m/, /f/  
Alveolar: /t/, /d/, /n/, /s/, /l/  
Palatal: /j/  
Velar: /k/, /ɡ/  
Labiovelar: /ɡb/, /w/  
Glottal: /ʔ/, /h/  

### By manner of articulation

Stops: /b/, /ɡb/, /t/, /d/, /k/, /ɡ/, /ʔ/  
Nasals: /m/, /n/  
Fricatives: /f/, /s/, /h/  
Approximants: /w/, /l/, /j/  

## Vowels

Vowels: /i/, /u/, /e/, /o/, /a/  

Amele contains the following diphthongs: /ai/, /au/, /ei/, /eu/, /oi/, /ou/; @AeyRoberts2016 interprets these as sequences of consecutive vowels rather than as complex phonemes. Other sequences of vowels can also occur (including consecutive identical vowels), but only across syllable boundaries [@AeyRoberts2016, pp. 66-68]. (@AeyRoberts1998 also argues for the existence of /ae/ and /ao/ as diphthongs (p. 3), but he seems to have moved away from that analysis by 2016.)

Mid vowels sometimes lengthen, but @AeyRoberts2016 finds the length to be a realization of an underlying sequence of identical vowels. (p. 75)

# Alphabet

The alphabet used is of the modern Amele orthography (developed ca. 1990), as the older orthography (developed in the 1920s) has several ambiguities; the modern orthography is also the one used by Crubadan, making it all the more preferable.

a - /a/  
b - /b/  
c - /ʔ/  
d - /d/  
e - /e/  
f - /f/  
g - /ɡ/  
h - /h/  
i - /i/  
j - /j/  
k - /k/  
l - /l/  
m - /m/  
n - /n/  
o - /o/  
q - /ɡb/  
r - /r/ (only used in Huar dialect)  
s - /s/  
t - /t/  
u - /u/  
w - /w/  

The older orthography also uses <p>, but because [p] is non-phonemic in Amele, I have excluded <p> from my ruleset.

# Lenition Rules

* In some words, /s/ alternates with [h] when adjacent to high vowels. [@AeyRoberts2016, p. 56]

# Misc. Rules

* Word-final non-alveolar stops devoice, if the word is multisyllabic; contrast between /ɡb/ and /b/ also collapses in such position, with both phonemes being realized as [p]. [@AeyRoberts2016, pp. 52-53, 64]
* /j/ goes to [ʒ] in certain circumstances: word-initially, when surrounded on both sides by /a/, word-finally after /i/, and intervocalically before /i/. [@AeyRoberts2016, p. 57]
* Word-final /w/ is realized as [ʋ]. [@AeyRoberts2016, p. 64]
* Consonant clusters can only occur word-medially. [@AeyRoberts2016, p. 65]
* Phonetically lax /a/ lengthens before voiced stops in monosyllabic words. [@AeyRoberts2016, p. 76]

# References
