---
title: "Zulu"
author: "Abi Creighton"
bibliography: zu.bib
output: html_document
---
#Background
**Language family**: Niger-Congo / Atlantic-Congo / Benue-Congo / Southern Bantoid / Bantu / Southern Bantu / Nguni / Zunda / Zulu

#Phonology

##Consonants
###Consonants by manner
Click: /|'/, /ǀʰ/, /ᵑǀ/, /ᶢǀʱ/, /ᵑǀʱ/, /ǁʼ/, /ǁʰ/, /ᵑǁ/, /ᶢǁʱ/, /ᵑǁʱ/, /!'/, /ǃʰ/, /ᵑǃ/, /ᶢǃʱ/, /ᵑǃʱ/
Nasal: /m/, /m̤/, /n/, /n̤/, /ɲ/
Stop: /p'/, /pʰ/, /b̤/, /ɓ/, /t'/, /tʰ/, /d̤/, /k'/, /kʰ/, /ɡ̈/, /ɠ/
Affricate: /ts'/, /tʃʼ/, /dʒ̈/, /kx'/
Fricative: /f/, /v̤/, /s/, /z̤/, /ɬ/, /ɮ̈/, /ʃ/, /h/, /ɦ̥/
Approximent: /l/, /j/, /j̈/, /w/, /w̤/
Trill: /r/ (only in borrowings)

###Consonants by place
Labial: /m/, /m̤/, /p'/, /pʰ/, /b̤/, /f/, /v̤/
Central dental/alveolar: /|'/, /ǀʰ/, /ᵑǀ/, /ᶢǀʱ/, /ᵑǀʱ/ /n/, /n̤/, /t'/, /tʰ/, /d̤/, /ts'/, /s/, /z̤/, /r/ 
Lateral dental/alveolar: /ǁʼ/, /ǁʰ/, /ᵑǁ/, /ᶢǁʱ/, /ᵑǁʱ/, /ɬ/, /ɮ̈/, /l/ 
Postalveolar: /!'/, /ǃʰ/, /ᵑǃ/, /ᶢǃʱ/, /ᵑǃʱ/, /ɲ/, /tʃʼ/, /dʒ̈/, /ʃ/, /j/, /j̈/
Velar: /k'/, /kʰ/, /ɡ̈/, /ɠ/, /kx'/, /w/, /w̤/
Glottal: /h/, /ɦ̥/

##Vowels
/i/, /u/, /e/, /o/, /a/, /ɛ/, /ɔ/

#Alphabet
A; a; /a/
B; b; /ɓ/
C; c; /ǀ/
D; d; /d/
E; e; /e/
F; f; /f/
G; g; /g/
H; h; /h/
I; i; /i/
J; j; /dʒ/
K; k; /k/ or /ɠ/
L; l; /l/
M; m; /m/
N; n; /n/
O; o; /o/
P; p; /p/
Q; q; /ǃ/
R; r; /r/
S; s; /s/
T; t; /t/
U; u; /u/
V; v; /v/
W; w; /w/
X; x; /ǁ/
Y; y; /j/
Z; z; /z/

#Rules
/e/ and /o/ are pronounced [e] and [o], respectively, if the following syllable contains an "i" or a "u" or if the vowel is word-final. They are [ɛ] and [ɔ] otherwise

n is velarized before clicks

## Lenition:
Labial and alveolar consonants are palatalized when followed by /j/. This results in some examples of spirantization:
pʰ > ʃ /_j
tʰ > ʃ /_j