---
title: "Huallaga Huánuco Quechua"
author: "Emily Strand"
bibliography: qub.bib
output: html_document
---

Last Updated: 2019-08-21

# Background

**Language Family**: Quechuan / Quechua I

# Phonology

## Consonants

* /b/, /d/, /g/, /f/, and /ʐ/ appear in loanwords [@weber_grammar_1989, pg. 450].
* Some sources indicate that /r/ is in fact an alveolar tap; however @weber_rimaycuna_2008 and @weber_grammar_1989 don't make this distinction, so I will recognize it as a trill.

### By place of articulation

Bilabial: /p/, /m/    
Alveolar: /t/, /n/, /r/, /s/, /l/  
Post-alveolar: /tʃ/, /ʃ/    
Palatal: /ɲ/, /j/, /ʎ/    
Velar: /k/, /w/   
Uvular: /q/   
Glottal: /h/   

### By manner of articulation

Stop: /p/, /t/, /k/, /q/  
Affricate: /tʃ/  
Fricative: /s/, /ʃ/, /h/
Nasal: /m/, /n/, /ɲ/   
Approximant: /j/, /w/   
Liquids: /l/, /ʎ/, /r/  

## Vowels

* Vowel length is contrastive. Long vowels are marked with a diareses (¨) [@weber_rimaycuna_2008, pg. 14].
* [e] and [o] are allophones of /i/ and /u/ respectively, or used in loanwords [@weber_grammar_1989, pg. 450].
* Vowels do not occur in succession [@weber_grammar_1989, pg. 455].

Short: /i/, /a/, /u/  
Long: /iː/, /aː/, /uː/  

# Alphabet

* There seems to be some debate as to what constitutes the Huallaga Huánuco Quechua alphabet. The Peruvian Ministry of Education publicly recognized the language in 2015, but the resources don't seem to be accessible. This could use another set of eyes.

a - /a/  
ä - /aː/  
b - /b/ (only in loanwords)  
c - /k/  
ch - /tʃ/  
d - /d/ (only in loanwords)  
e - /i/; /e/ (only in loanwords)
ë - /iː/; /eː/ (only in loanwords)
f - /f/ (only in loanwords)  
g - /q/; /g/ (only in  loanwords)  
  gu - /q/  
h - /h/  
i - /i/  
ï - /iː/  
j - /h/  
l - /l/  
ll - /ʎ/  
m - /m/  
n - /n/  
ñ - /ɲ/  
o - /u/  
ö - /uː/  
p - /p/  
qu - /k/  
r - /r/  
rr - /ʐ/ (only in loanwords)  
sh - /ʃ/  
s - /s/  
t - /t/  
u - /u/  
ü - /uː/  
w - /w/  
y - /j/  

# Syllable Structure

* The syllable structure consists of (C)V(C). The onset is required except in an initial syllable [@weber_grammar_1989, pg. 454].

# Lenition Rules

* /g/ changes to /w/ intervocalically [@weber_grammar_1989, pg. 476].
* /q/ fricates word-finally or preceding a voiceless obstruent [@weber_grammar_1989, pg. 452].
