---
title: "Tarahumara"
author: "Bill Mizgerd"
bibliography: tac.bib
output: html_document
---

Last Updated: 2019-06-24

# Background

**Language Family**: Uto-Aztecan / Southern Uto-Aztecan / Tarahumaran / Tarahumara

Where dialects diverge, I will be preferring Western Tarahumara, which is only the second most widely spoken dialect but is the dialect with the most robust Crubadan corpus.

# Phonology

## Consonants

### By place of articulation

Labial: /p/, /m/, /β/, /w/  
Alveolar: /t/, /n/, /s/  
Postalveolar: /tʃ/  
Retroflex: /ɽ/, /ɭ/  
Palatal: /j/  
Velar: /k/, /ɣ/  
Glottal: /ʔ/, /h/  

### By manner of articulation

Stops: /p/, /t/, /k/, /ʔ/  
Affricates: /tʃ/  
Nasals: /m/, /n/  
Fricatives: /β/, /s/, /ɣ/, /h/  
Flaps: /ɽ/  
Approximants: /w/, /ɭ/, /j/  

## Vowels

Vowels: /i/, /e/, /u/, /o/, /a/  

# Alphabet

a - /a/  
b - /β/  
ch - /tʃ/  
e - /e/  
g - /ɣ/  
h - /h/  
i - /i/  
k - /k/  
l - /ɭ/  
m - /m/  
n - /n/  
o - /o/  
p - /p/  
r - /ɽ/  
s - /s/  
t - /t/  
u - /u/  
w - /w/  
y - /j/  
' - /ʔ/  

Loanwords sometimes contain <f q z>. [@TacThordGray1955, pp. 26-27]

## Spanish Orthography

Some orthographies use spellings more based on the Spanish orthography, as shown below. [@TacThordGray1955, p. 1157]

c - /k/  
hu - /w/  
j - /h/  
qu - /k/  

# Lenition Rules

* When between stressed high vowels and glottal stops, word-initial /a/ reduces to [ə]. [@TacBurgess1984, p. 8]
* Unstressed vowels often delete in fast speech. (ibid.)
* Unstressed vowels in non-initial syllables delete when preceded by a nasal and followed by a stop. (ibid.)
* Word-initial stops are sometimes voiced. [@TacThordGray1955, pp. 26-27]
* /t/ sometimes approximantizes to [ɽ]. (ibid.)
* Before high or front vowels, /tʃ/ spirantizes to [ʃ]. [@TacValdezJara2013, p. 20]

# Misc. Rules

* /β/ and /ɣ/ despirantize word-initially to [b] and [ɡ] respectively. [@TacBurgess1984, p. 7]
* Phrase-initial /ɽ/ is often produced as [r] or, less commonly, [ɾ]. (ibid.)
* In phrase-initial syllables, unstressed vowels lengthen unless they're followed by a vowel or glottal consonant. [@TacBurgess1984, p. 8]
* /i/ lowers in unstressed non-initial syllables. (ibid.)
* Epenthesis of [j] typically occurs before word-initial vowels. [@TacThordGray1955, pp. 26-27]
* /h/ is often realized as [x]. [@TacValdezJara2013, p. 21]

# References
