---
title: "tk.rmd"
author: "Abi Creighton"
date: "April 17, 2019"
bibliography: tk.bib
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Background
**Language family**: Turkic / Common Turkic / Oghuz / Eastern Oghuz / Turkmen

Turkmen has three writing systems: Latin, Cyrllic, and Arabic [@schonig_turkmen_1998]. The Latin alphabet was adopted in 1993 as the official script of the Turkmen language, but the Cyrillic script is still widely in use. The Arabic alphabet has been phased out since 1929, but it is still used to write Turkmen in countries such as Iran and Afghanistan in which Arabic is the dominant script. However, many Turkmen speakers in these countries using the Arabic script speak a distinct dialect, so this document will only address the Latin and Cyrllic writing systems. 

#Phonology
Sources for inventory and orthography: [@gray_turkmen_1994] and [@hoey_grammatical_2013]

##Consonants
###Consonants by place
Bilabial: /m/, /p/, /b/, /w/
Labiodental: /f/
Dental: /n/, /t̪/, /d̪/, /θ/, /ð/, /l/
Alveolar: /t͡ʃ/, /d͡ʒ/, /ʃ/, /ʒ/, /r/
Palatal: /j/
Velar: /ŋ/, /k/, /g/, 
Glottal: /h/

###Consonants by manner
Nasal: /m/, /n/, /ŋ /
Stop: /p/, /b/, /t/, /d/, /k/, /g/
Fricative: /f/, /θ/, /ð/, /ʃ/, /ʒ/, /h/
Afficates: /t͡ʃ/, /d͡ʒ/
Approximants: /w/, /l/, /j/
Rhotic: /ɾ/

##Vowels
Front close: /ɪ/, /ɪː/, /ʏ/, /ʏː/
Back close: /ɯ/, /ɯː/, /ʊ/, /ʊː/
Front mid: /ɛ/, /œ/, /œː/
Back mid: /o/, /oː/
Front open: /æː/
Back open: /ɑ/, /ɑː/

#Latin Alphabet
A a: /ɑ/
B b: /b/
Ç ç: /t͡ʃ/
D d: /d̪/
E e: /ɛ/
Ä ä: /æ/
F f: /f/
G g: /g/
H h: /x/
I i: /ɪ/
J j: /d͡ʒ/
Ž ž: /ʒ/
K k: /k/ 
L l: /l/
M m: /m/
N n: /n/
Ň ň: /ŋ/
O o: /o/
Ö ö: /œ/
P p: /p/
R r: /ɾ/
S s: /θ/
Ş ş: /ʃ/
T t: /t̪/
U u: /ʊ/
Ü ü: /ʏ/
W w: /β/ (only in Russian words)
Y y: /ɯ/
Ý ý: /j/
Z z: /ð/

#Cyrillic Alphabet
А а: /ɑ/
Б б: /b/
Ч ч: /t͡ʃ/
Д д: /d̪/
Э э: /ɛ/ (initially)
Е е: /ɛ/ (non initially)
Ә ә: /æ/
Ф ф: /f/
Г г: /g/
Х х: /x/
И и: /ɪ/
Җ җ: /d͡ʒ/
Ж ж: /ʒ/
К к: /k/ 
Л л: /l/
М м: /m/
Н н: /n/
Ң ң: /ŋ/
О о: /o/
Ө ө: /œ/
П п: /p/
Р р: /ɾ/
С с: /θ/
Ш ш: /ʃ/
Т т: /t̪/
У у: /ʊ/
Ү ү: /ʏ/
В в: /β/ (only in Russian words)
Ы ы: /ɯ/
Й й: /j/
З з: /ð/

#Rules
-Turkmen has vowel harmony. Native words generally -consist only of front or back vowels. 
-Utterance final consonants are unreleased. 
-Stress is usually on the last syllable of the root.
-There are no word initially consonant clusters

## Lenition
From Gray (1994):
X --> [+voice] /_V when X =p,t,k,tʃ
g --> ɣ word internally

From Schönig (1998):
b --> w / V_V or between a liquid and a vowel 
b --> [-voice] /_#
d --> [-voice] /_#
Suffix-initial b,d, and g are devoiced after stem-final voiceless sounds

