---
title: "Chʼortiʼ"
author: "Emily Strand"
bib: caa.bib
output: html_document
---

Last updated: 09-12-2019

# Background

**Language family**: Mayan / Cholan-Tzeltalan / Cholan / Chorti

# Phonology

## Consonants

* Although /g/ and /w/ were once considered allophones in Chʼortiʼ and still occur in free variation in some environments (eg. preceding /o/), they are classified as distinct phonemes [@hull_dictionary_2016, pg. 8].
* There is some ambiguity around the phonemes /h/ and /x/. Sources indicate either as being represented by ⟨j⟩, but I have opted to follow @hull_dictionary_2016 and @dugan_grammar_2013 in using /h/ (pg. 7; pg. 18).
* /b/, /d/, and /g/ are said to appear mainly in Spanish loanwords [@dugan_grammar_2013, pg. 18]; however, I have opted to include them, just as @hull_dictionary_2016 does (pg. 7).

### By place of articulation

Bilabial: /p/, /b/, /ɓ/, /m/  
Alveolar: /t/, /tʼ/, /d/, /s/, /ts/, /tsʼ/, /n/, /r/, /l/  
Post-alveolar: /ʃ/, /tʃ/, /tʃʼ/, /j/  
Velar: /k/, /kʼ/, /g/, /w/  
Glottal: /ʔ/, /h/  

### By manner of articulation

Stop: /p/, /b/, /ɓ/, /t/, /tʼ/, /d/, /k/, /kʼ/, /g/, /ʔ/  
Fricative: /s/, /ʃ/, /h/  
Affricate: /ts/, /tsʼ/, /tʃ/, /tʃʼ/  
Nasal: /m/, /n/  
Trill: /r/  
Approximant: /l/, /j/, /w/  

## Vowels

* Vowel length is not necessarily contrastive in Chʼortiʼ. Although long vowels can arise in the environment where a glottal stop follows, it's not obligatory [@marhenke_typescript_2019, pg. 8]. In fact, the glottal stop in such positions is pronounced lenis, often followed by rearticulation of the vowel (ibid.). Therefore, I will be treating all vowels (⟨a'⟩, ⟨e'⟩, ⟨i'⟩, ⟨o'⟩, ⟨u'⟩) as the vowel followed by a glottal stop.
* Vowel length is sometimes indicated by an accent mark over the vowel or by a postvocalic ⟨h⟩ [@Fought2012, pg. 45]. However, given that vowel length is not contrastive, such accented vowels will be transcribed as short vowels. In addition, the postvocalic ⟨h⟩ is purely used to separate elements, thus it has no phonemic realization (ibid.).  
* Diphthongs are said to be present in Chʼortiʼ [@marhenke_typescript_2019, pg. 10], which are always written with a vowel and a glide [@dugan_grammar_2013, pg. 28]. @dugan_grammar_2013 expresses the fact that they are largely uncommon in the language (pg. 18); so, given this and the fact that there isn't a wide consensus on the inventory, I won't include them in the analysis.

Vowels: /i/, /e/, /a/, /o/, /u/

# Alphabet

a - /a/  
b - /b/  
b' - /ɓ/   
d - /d/    
e - /e/  
g - /g/  
i - /i/  
j - /h/  
k -  /k/  
k' - /kʼ/   
l - /l/  
m - /m/  
n - /n/  
o - /o/  
p - /p/  
r - /r/  
s - /s/  
t - /t/  
t' - /tʼ/  
u - /u/  
w - /w/  
x - /ʃ/   
y - /j/  
ʼ - /ʔ/  

## Digraphs

ch - /tʃ/   
chʼ - /tʃʼ/    
tz - /ts/    
tzʼ - /tsʼ/

## Orthographic Variation

c - /k/ (realized as /s/ in Spanish loanwords)
c' - /kʼ/
qu - /k/
q'u - /kʼ/   

# Lenition Rules

* /h/ is often deleted word-initially [@hull_dictionary_2016, pg. 8].
* Glottal stops are often unpronounced within the first syllable and word-finally [@hull_dictionary_2016, pg. 8-9].

# Misc Rules

* /l/ and /r/ often appear in free variation [@hull_dictionary_2016, pg. 7].
