---
title: "Slovak"  
author: "Emily Strand"  
bibliography: sk.bib  
output: html_document  
---

Last updated: 2019-07-26  

# Background  

**Language Family**: Indo-European / Slavic / West/ Czech-Slovak  

Also known as Slovakian.

# Phonology  


## Consonants  

* @rubach_lexical_1993 states that the palatal consonants of ⟨ť⟩, ⟨ď⟩, ⟨ľ⟩, and ⟨ň⟩ are in fact prepalatal (pg. 30); however, given that   @hanulikova_slovak_2010 and @short_slovak_1993 didn't make this distinction, based on the fact that they rarely contrast [@wiki:xxx], I went with the standard palatal IPA symbols (pg. 374; pg. 535).  
* [@hanulikova_slovak_2010] makes the point that even though [lː] and [rː] are often considered allophones of /l/ and /r/ respectively, they don't appear in complementary distribution (pg. 374). Based on this, I will keep the phonemic distinction.  

### By place of articulation  

Bilabial: /p/, /b/, /m/  
Labiodental: /f/, /v/  
Alveolar: /t/, /d/, /n/, /s/, /z/, /t͡s/, /d͡z/, /r/, /rː/, /l/, /lː/  
Post-Alveolar: /ʃ/, /ʒ/, /t͡ʃ/, /d͡ʒ/  
Palatal: /c/, /ɟ/, /ɲ/, /j/, /ʎ/  
Velar: /k/, /g/, /x/  
Laryngeal: /ɦ/  

### By manner of articulation  

Stops: /p/, /b/, /t/, /d/, /c/, /ɟ/, /k/, /g/  
Nasals: /m/, /n/, /ɲ/  
Affricates: /t͡s/, /d͡z/, /t͡ʃ/, /d͡ʒ/  
Fricatives: /f/, /v/, /s/, /z/, /ʃ/, /ʒ/, /x/, /ɦ/  
Trill: /r/, /rː/  
Approximant: /j/  
Lateral Approximant: /l/, /lː/, /ʎ/  

## vowels  

* @hanulikova_slovak_2010 and @short_slovak_1993 express that /æ/ (grapheme: ⟨ä⟩) is virtually obsolete in the language and is realized more often as /ɛ/ (pg. 375; pg. 534). Therefore, I will use /ɛ/ to represent the grapheme ⟨ä⟩.  
* Slovak makes a distinction between long and short vowels [@hanulikova_slovak_2010, pg. 534]. Long vowels are indicated with acute accents (´).  
* /ʊɔ/ is the only dipthong that is realized by an individual grapheme [@hanulikova_slovak_2010, pg. 376].  

Vowels: /i/, /a/, /ɛ/, /ɔ/, /u/  

Dipthongs: /ia/, /iɛ/, /iu/, /ʊɔ/  

# Alphabet  

* The Slovak alphabet is considered phonemic [@rubach_lexical_1993, pg. 30]  
* @rubach_lexical_1993 had the clearest transcription between graphemes and IPA (pg. 31). I based the vowel transcription heavily on that source.
* Regarding the graphemes of the palatal consonants ⟨ť⟩, ⟨ď⟩, ⟨ľ⟩, and ⟨ň⟩, the diacritics aren't present when preceding front vowels [@rubach_lexical_1993, pg. 30]. Although this creates some ambiguity in terms of the phonemic transcription, I decided that the language was still usable.  
* Graphemes containing two characters (ie. dz) represent one phoneme when not situated at a morpheme boundary. If situated at a morpheme boundary, they are independent graphemes [@altmann_phoneme-grapheme_2008, pg. 80].  
* Notice that the uppercase correspondents of ⟨d'⟩ and ⟨tˈ⟩ are ⟨Ď⟩ and ⟨Ť⟩.

A, a - /a/  
Á, á - /aː/  
Ä, ä - /ɛ/  
B, b - /b/  
C, c - /t͡s/  
Č, č - /t͡ʃ/  
D, d - /d/  
Ď, ď - /ɟ/  
Dz, dz - /d͡z/  
Dž, dž - /d͡ʒ/  
E, e - /ɛ/  
É, é - /ɛː/  
F, f - /f/  
G, g - /g/  
H, h - /ɦ/  
CH, ch - /x/  
I, i - /i/  
Í, í - /iː/  
J, j - /j/  
K, k - /k/  
L, l - /l/  
Ĺ, ĺ - /lː/  
L', ľ - /ʎ/  
M, m - /m/  
N, n - /n/  
Ň, ň - /ɲ/  
O, o - /ɔ/  
Ó, ó - /ɔː/  
Ô, ô - /ʊɔ/  
P, p - /p/  
Q, q - /k/ or /kv/ (only in loanwords)  
R, r - /r/  
Ŕ, ŕ - /rː/  
S, s - /s/  
Š, š - /ʃ/  
T, t - /t/  
Ť, tˈ - /c/  
U, u - /u/  
Ú, ú - /uː/  
V, v - /v/ or /w/ (only in loanwords)  
W, w - /v/  
X, x - /ks/ or /gz/ (only in loanwords)  
Y, y - /i/  
Ý, ý - /iː/  
Z, z - /z/  
Ž, ž - /ʒ/  


# Lenition Rules

* /g/ spirantizes to /ɣ/ [@short_slovak_1993, pg. 536]
* /v/ approximates to [ʋ] in syllable onset preceding a vowel or liquid [@hanulikova_slovak_2010, pg. 374]. It also approximates to [ʋ] or [w] in coda positions.
* Long vowels shorten if preceded by a long vowel and glides [@rubach_lexical_1993, pg. 43 - 4].
* In verbs, the preceding vowel in a vowel cluster deletes [@rubach_lexical_1993, pg. 45].

# Misc. Rules

* Velars and coronals palatalize before front vowels and glides [@rubach_lexical_1993, pg. 44].
* Alveolar fricatives palatalize and alveolar stops become affricates preceding /j/. However, if such stops are preceded by an alveolar fricative, they palatalize [@rubach_lexical_1993, pg. 44].
* There is final devoicing of voiced obstruents [@hanulikova_slovak_2010, pg 376]. /ɦ/ is realized as [x] in this case.
* /n/ assimilates to [ɲ] prior to velar sounds [@hanulikova_slovak_2010]
* /n/ assimilates to [m] prior to labials [@hanulikova_slovak_2010]
* Obstruents assimilate in voicing (the preceding obstruent must assimilate to the following obstruent) [@rubach_lexical_1993, pg. 30]. There is an exception with /v/ if preceded in syllable onset [@hanulikova_slovak_2010, pg. 376]. /ch/ becomes [ɣ] in this case if voicing is required.
