---
title: "Wayuu"
author: "Emily Strand"
bibliography: guc.bib
output: html_document
---

# Background

**Language family**: Arawakan / Maipuran / Northern / Caribbean / Guajiro-Paraujano

Also referred to as Goajiro and Wayuunaiki.

# Phonology

## Consonants

* Some documentation includes /β/ and /ɲ/ as phonemes corresponding to ⟨v⟩ and ⟨ñ⟩ respectively [Hildebrandt and de Uterga in @sabogal_variable_2018, pg. 50-52]. However, given that other authors omit them from the phonemic inventory, citing them as allophones of /w/ and /n/ respectively, forming no minimal pairs [@alvarez_manual_2017, pg. 18; @sabogal_variable_2018, pg. 50, 52], I have also chosen to exclude them.
* Excluding /h/, /r/, /w/, and /j/, consonants can geminate [@holmer_goajiro_1949, pg. 49].

### By place of articulation

Labial: /p/, /m/, /w/  
Alveolar: /n/, /t/, /s/, /r/  
Post-alveolar: /ɺ/, /tʃ/, /ʃ/  
Palatal: /j/  
Velar: /k/  
Glottal: /ʔ/, /h/  

### By manner of articulation

Stop: /p/, /t/, /k/, /ʔ/  
Nasal: /m/, /n/  
Affricate: /tʃ/  
Fricative: /s/, /ʃ/, /h/  
Flap: /ɺ/  
Trill: /r/  
Approximant: /w/, /j/  

## Vowels

* Vowel length is contrastive. Long vowels are indicated by repeated graphemes [@sabogal_variable_2018, pg. 49].
* There is some debate as to whether /ɯ/ or /ɨ/ corresponds to ⟨ü⟩. Whereas @mansen_aprendamos_1984 opts for /ɨ/ (pg. 4), @alvarez_manual_2017 and @sabogal_variable_2018 opt for /ɯ/ (pg. 18; pg. 49). I have chosen to use /ɯ/, which is more consistent with recent documentation.
* Rising vowel sequences can be pronounced as diphthongs or independent monophthongs - the pronunciation is in free variation [@sabogal_variable_2018, pg. 50].
* Vowel harmony is present in Wayuu, structured on the basis of fronting and rounding [@sabogal_variable_2018, pg. 53].
* Vowels often become nasalized; however, the meaning does not change whether they are pronounced orally or nasally [@mansen_aprendamos_1984, pg. 9].

/i/, /e/, /ɯ/, /a/, /u/, /o/  

# Alphabet

a - /a/  
e - /e/  
i - /i/  
j - /h/  
k - /k/  
l - /ɺ/  
m - /m/  
n - /n/  
o - /o/  
p - /p/  
r - /r/  
s - /s/  
t - /t/  
u - /u/  
ü - /ɯ/  
w - /w/  
y - /j/  
' - /ʔ/  

# Digraphs

ch - /tʃ/  
sh - /ʃ/  


# Lenition Rules

* /k/ and /p/ become voiced preceding /ɺ/ [@holmer_goajiro_1949, pg. 49].
* /ɺ/ becomes /r/ preceding front vowels [@sabogal_variable_2018, pg. 60].
* /ɺ/ is unpronounced when preceding a monomaraic (short) /i/ [@sabogal_variable_2018, pg. 60].
* Word-final vowels and vowels preceding /s/, /tʃ/, and /ʃ/ are often pronounced lenis or unpronounced [@holmer_goajiro_1949, pg. 50].

# Misc Rules

* Vowel elision and liquid fortition often occur in tandem [@sabogal_variable_2018, pg. 59,60]. First, vowels are elided when preceding a liquid and following an obstruent. Then, with the resulting liquid-obstruent sequence, the liquid becomes /t/ (or assimilates to /n/ if the obstruent was an /n/).
