---
title: "Javanese"
author: "Bill Mizgerd"
bibliography: jv.bib
output: html_document
---

Last Updated: 2019-02-08

# Background

**Language Family**: Austronesian / Malayo-Polynesian / Javanese

# Phonology

## Consonants

### By place of articulation

Bilabial: /p/, /b/, /mb/, /m/, /w/  
Dental/Alveolar: /t̪/, /d̪/, /nd̪/, /n/, /s/, /l/, /r/  
Retroflex: /ʈ/, /ɖ/, /nɖ/  
Palatal: /c/, /ɟ/, /nɟ/, /ɲ/, /j/  
Velar: /k/, /ɡ/, /ŋ/, /ŋɡ/  
Glottal: /ʔ/, /h/  

@JvSuharno1982 uses /q/ instead of /ʔ/, but describes the consonant as glottal; @JvNothofer1975 also uses /q/, but in his table gives it the same place of articulation as /h/. For these reasons, I have followed the pattern of the authors (Wolff, Horne, Robson) who prefer /ʔ/.

### By manner of articulation

Stops: /p/, /b/, /t̪/, /d̪/, /ʈ/, /ɖ/, /c/, /ɟ/, /k/, /ɡ/, /ʔ/
Stops (pre-nasalize): /mb/, /nd̪/, /nɖ/, /nɟ/, /ŋɡ/
Nasals: /m/, /n/, /ɲ/, /ŋ/  
Fricatives: /s/, /h/  
Laterals: /l/  
Trills: /r/  
Glides: /w/, /j/  

I have chosen to include dental and retroflex stops, but not alveolar stops. The authors I've read have disagreed about which of the aforementioned stops do occur in Javanese; all agree, however, that exactly two of the three places of articulation are represented. Dental and retroflex is the pair that I find to be likeliest.

@JvHorne1974: Dental, alveolar  
@JvNothofer1975: Alveolar, retroflex(?)  
@JvRobson2014: Dental, retroflex  
@JvSuharno1982: Dental, retroflex  
@JvWolffChart1982: Dental, alveolar  

### Other notes on consonants

Additional phonemes, per @JvWolffChart1982:  
Prenasalized stops: /mb/, /nd̪/, /nɖ/, /nɟ/, /ŋɡ/{1}  
Lenis continuants (pharyngealized): /wh/, /nh/, /lh/, /rh/, /jh/ (Unattested elsewhere, so I have not included them in the ruleset)  
Sounds found only in loanwords: /f/, /z/  

{1}: Wolff does not depict this consonant as assimilating, but Nothofer and Horne do. Because (at least some) other prenasalized stops feature nasal assimilation, and because /ŋ/ is phonemic in Javanese, I have followed his example. Although I have not seen explicit attestation of nasal assimilation in the rest of the prenasalized stops, I find it to be likely enough that I have included it in my ruleset.

## Vowels

High vowels: /i/, /u/  
Mid vowels: /e/, /o/  
Mid-low vowels: /ɛ/, /ə/, /ɔ/  
Low vowels: /a/  

Vowels may occur successively, but they do not form diphthongs when doing so. [@JvSuharno1982, page 2]

## Stress

Stress falls on the penult, unless the vowel of the penult is /ə/, which is never stressed in Javanese. [@JvRobson2014, page xvi]

# Alphabet

## Phonemic

a - /a/  
b - /b/  
c - /c/ (described by Horne as /t̪s/)  
d - /d̪/  
e - /ə/  
é - /e/  
è - /ɛ/  
f - /f/ (only in loanwords; sometimes replaced by /p/; see @JvHorne1974, page xi)  
g - /ɡ/  
h - /h/  
i - /i/  
j - /ɟ/ (described by Horne as /d̪z/)  
k - /k/  
l - /l/  
m - /m/  
n - /n/  
o - /o/  
ô - /ɔ/ (unattested in Crubadan corpus, and hence omitted from ruleset)  
p - /p/  
q - /ʔ/ (only in loanwords)  
r - /r/  
s - /s/  
t - /t̪/  
u - /u/  
v - /f/ (only in loanwords; per Horne, is an alternate spelling of <f>)  
w - /w/  
y - /j/  

### Digraphs

dh - /ɖ/  
mb - /ᵐb/  
nd - /ⁿd̪/  
ng - /ŋ/  
nj - /ᶮɟ/  
ny - /ɲ/  
th - /ʈ/  

Some transcriptions use <ḍ> and <ṭ> in place of <dh> and <th>.

### Trigraphs

ndh - /ⁿɖ/  
ngg - /ᵑɡ/  

# Javanese Script

A ruleset for the Javanese abugida is also provided at jv-jscript.rules. Note that, because Crubadan's only Javanese corpus uses the Latin script, the Javanese-script ruleset is not as thoroughly tested as its Latin-script counterpart.

The phonology of the Javanese script is taken from @JvOmniglot and @JvRomanization.

## Consonants

ꦲ - /h/ (also used as the zero consonant in word-initial contexts)  
ꦤ - /n/  
ꦕ - /c/  
ꦫ - /r/  
ꦏ - /k/  
ꦢ - /d̪/  
ꦠ - /t̪/  
ꦱ - /s/  
ꦮ - /w/  
ꦭ - /l/  
ꦥ - /p/  
ꦣ - /ɖ/  
ꦗ - /ɟ/  
ꦪ - /j/  
ꦚ - /ɲ/  
ꦩ - /m/  
ꦒ - /ɡ/  
ꦧ - /b/  
ꦛ - /ʈ/  
ꦔ - /ŋ/

### Consonant Diacritics

These predominantly form the codas of their syllables.

ꦀ - /m/  
ꦁ - /ŋ/  
ꦂ - /r/  
ꦃ - /h/  
ꦽ - /rə/  
ꦾ - /j/  
ꦿ - /r/

꧀ - ∅ (nullifies the vowel in its syllable)

## Vowels

ꦄ - /a/  
ꦆ - /i/  
ꦈ - /u/  
ꦌ - /e/  
ꦎ - /o/

### Vowel Diacritics

In the absence of a vowel diacritic, /a/ is taken as the "default" vowel for a syllable.

ꦶ - /i/  
ꦸ - /u/  
ꦺ - /e/  
ꦺ - /o/  
ꦼ - /ə/  

Despite being present in the Latin script, /ɛ/ does not seem to be attested in the Javanese script.

## Newer Aksara

ꦉ - /rə/  
ꦊ - /lə/

# More Rules

Syllables take the format (CC)V(C).

* The following consonants do not occur word-finally [@JvSuharno1982, page 6]:
  * Voiced stops (due to word-final devoicing)
  * Palatal and retroflex consonants
  * Glides
  * /h/
  * Any consonant cluster
* Conversely,
* /e/ and /ɛ/ do not occur word-finally; /a/ only occurs word-finally in the word <ora> [@JvSuharno1982, page 6]
* Except in interjections, /ə/ never occurs word-finally or before /ʔ/ [@JvNothofer1975, page 9]
* /ʔ/ always appears word-finally, except in interjections where it can be intervocalic [@JvNothofer1975, page 9]
* /h/ only occurs word-initially in interjections or loanwords [@JvRobson2014, page xvi]
* /ʔ/ inserted before the suffix <-aké> or after the prefix <sa-> [@JvRobson2014, page xvi]
* Nasal prefixes added to many verb forms [@JvRobson2014, p. 12]

## Lenition rules

* /h/ deleted intervocalically if between non-identical vowels [@JvRobson2014, page xvi]
* word-final /k/ debuccalizes to [ʔ]

### Vowel Lenition

* tense vowels become lax in closed syllables [@JvHorne1974, page xi]

# Examples

**/h/-deletion:**  
lungguh - /luᵑɡuh/ - to sit; lungguhan - /luᵑɡuan/ - sitting  
mulih - /mulih/ - to return home; mulihé - /mulie/ - his return

# References
