---
title: "Mapudungun"
author: "Emily Strand"
bibliography: arn.bib
output: html_document
---

Last updated: 2019-10-01

# Background

**Language family**: Araucanian

Also referred to as Mapuche or Araucana.

# Phonology

## Consonants

* In some dialects of Mapudungun, the distinction between the dental and alveolar phonemes have merged [@sadowsky_mapudungun_2013, pg. 89], leaving the dentals to appear as a result of allophonic variation.
* /ʃ/ is rather infrequent, often alternating with /s/ yet it is still considered in most sources to be a phoneme [@smeets_grammar_2008 pg. 23].

### By place of articulation

Labial: /p/, /f/, /m/  
Dental: /t̪/, /θ/, /n̪/, /l̪/  
Alveolar: /t/, /s/, /n/, /l/  
Postalveolar: /tʃ/, /ʃ/  
Retroflex,: /ʈʂ/, /ʐ/  
Palatal: /j/, /ʎ/, /ɲ/  
Velar: /k/, /ŋ/, /ɣ/, /w/  

### By manner of articulation

Stops: /p/, /t̪/, /t/, /k/  
Nasals: /m/, /n̪/, /n/, /ɲ/, /ŋ/  
Affricates: /tʃ/, /ʈʂ/  
Fricatives: /f/, /θ/, /s/, /ʃ/, /ʐ/, /ɣ/  
Approximants: /l̪/, /l/, /j/, /ʎ/, /w/  

## Vowels

* Diphthongs aren't prevalent in Mapudungun; however, the sequence /ae/ is usually realized as one [@smeets_grammar_2008, pg. 52].

/i/, /e/, /ɘ/, /a/, /u/, /o/  

# Alphabet

* Although there isn't a standardization of the alphabet, the three alphabets commonly referred to provide a rather comprehensive picture in terms of depicting each phoneme. These alphabets include the Alfabeto Mapuche Unificado, the Frafemario Raguileo, and the Azumchefi [@bronzino_loanword_nodate, pg. 22]. Listed below is the Alfabeto Mapuche Unificado, but following it I have provided the orthographic variations from the other two.
* Regarding the corresponding phoneme of <g>, the Unified Alphabet uses /ɣ/ whereas the Raguileo and Azumchefi alphabets use /ŋ/. I went with the <g> to /ŋ/ correspondence because the Crubadan corpus includes the grapheme <q> which isn't accounted for in the Unified Alphabet but is in the other two, having a phoneme correspondence of /ɣ/.
* The dentals are not represented in the Crubadan corpus based on the Unified Alphabet graphemes. With the grapheme correspondences of the other two alphabets, they appear (except /t̪/, as the distinction between it at /t/ is not maintained in either).


a - /a/  
d - /θ/  
e - /e/  
f - /f/  
g - /ŋ/  
i - /i/  
ï - /ɘ/  
k - /k/  
l - /l/  
ḻ - /l̪/  
m - /m/  
n - /n/  
ṉ - /n̪/  
ñ - /ɲ/  
o - /o/  
p - /p/  
r - /ʐ/  
s - /s/  
t - /t/  
ṯ - /t̪/  
u - /u/  
ü - /ɘ/  
w - /w/  
y - /j/  

## Digraphs

ch - /tʃ/  
tr - /ʈʂ/  
sh - /ʃ/  
ng - /ŋ/  
ll - /ʎ/  

## Orthographic Variations

c - /tʃ/    (Raguileo)  
x - /ʈʂ/    (Raguileo)  
tx - /ʈʂ/   (Azumchefi)  
z - /θ/     (Raguileo and Azumchefi)   
h - /n̪/     (Raguileo)  
nh - /n̪/    (Azumchefi)  
q - /ɣ/     (Raguileo and Azumchefi)  
b - /l̪/     (Raguileo)  
lh - /l̪/    (Azumchefi)  
j - /ʎ/     (Raguileo)   
v - /ɘ/     (Raguileo)  


# Lenition Rules

* Unstressed vowels are often deleted in word-final positions following voiceless consonants [@sadowsky_mapudungun_2013, pg. 94].
* /ɘ/ may be deleted following a stressed syllable (ibid.).
* Geminates occur in the language, but often they are realized as single consonants [@smeets_grammar_2008, pg. 51].
* The velar phonemes /k/, /ŋ/, /ɣ/ tend to be fronted preceding front vowels [@sadowsky_mapudungun_2013, pg. 89].
* /ʐ/ can approximate to /ɻ/ [@sadowsky_mapudungun_2013, pg. 90].

# Misc Rules

* Aspiration of some of the stops can occur [@sadowsky_mapudungun_2013, pg. 89].
* Consonant clusters are only allowed intervocalically [@smeets_grammar_2008, pg. 37, 38].
