---
title: "Georgian"
author: "Maddie Critz"
date: "October 9, 2018"
bibliography: ka.bib
output: html_document
---

Last updated: 2019-10-31

# Background

**Language Family** : Kartvelian / Karto-Zan / Georgian

* Georgian is spoken throughout the country of Georgia.

# Phonology

## Consonants

```{r echo=FALSE, message=FALSE, warning=FALSE, results = 'asis'}

library(dplyr)
library(knitr)
library(kableExtra)


consonants <- read.table(textConnection('
"Manner of Articulation"      Labial      Alveolar    Postalveolar       Velar       Uvular   Glottal   
Stops                      "pʰ  p’  b"  "tʰ  t’  d"       ""          "kʰ  k’  ɡ"     "q’"      ""
Affricates                     ""      "ts  ts’  dz" "tʃ  tʃ’  dʒ"        ""          ""        ""
Fricatives                     "v"        "s  z"        "ʃ  ʒ"           "x  ɣ"       ""        "h"
Nasals                         "m"         "n"            ""              ""          ""        ""
Flaps                          ""          "ɾ"            ""              ""          ""        ""
Approximants                   ""          "l"            ""              ""          ""        ""
'), TRUE)

kable(consonants, col.names = c("Manner of Articulation", "Labial", "Alveolar", "Postalveolar", "Velar", "Uvular", "Glottal"), align = 'c') %>%
  kable_styling("bordered") %>%
  add_header_above(c("", "Place of Articulation" = 6)) %>%
  column_spec(1, bold = TRUE) %>%
  footnote(general = "Note: Phonemes that have the diacritics (ʰ) or (') are aspirated and ejective, respectively.", general_title = "")
```

## Vowels

```{r echo=FALSE, message=FALSE, warning=FALSE, results = 'asis'}

vowels <- read.table(textConnection('
         Front      Back
High      "i"       "u"
Mid       "ɛ"       "ɔ"
Low        ""       "ɑ"
'), TRUE)

kable(vowels, align = 'c') %>%
  kable_styling("bordered") %>%
  column_spec(1, bold = TRUE)
```  

# Alphabet

```{r echo=FALSE, message=FALSE, warning=FALSE, results = 'asis'}

alphabet <- read.table(textConnection('
Grapheme      Phoneme  
"ა"		         "/ɑ/"
"ბ"		         "/b/"
"გ"		         "/ɡ/"
"დ"		        "/d/"
"ე"		         "/ɛ/"
"ვ"		         "/v/"
"ზ"		        "/z/"
"თ"		        "/tʰ/"
"ი"	           "/i/"
"კ"	          "/k’/"
"ლ"	          "/l/"
"მ"	          "/m/"
"ნ"		        "/n/"
"ო"		        "/ɔ/"
"პ"		        "/pʼ/"
"ჟ"		        "/ʒ/"
"რ"		        "/ɾ/"
"ს"		        "/s/"
"ტ"		       "/tʼ/"
"უ"		        "/u/"
"ფ"		       "/pʰ/"
"ქ"		       "/kʰ/"
"ღ"		       "/ɣ/"
"ყ"		       "/q’/"
"შ"		        "/ʃ/"
"ჩ"		       "/tʃʰ/"
"ც"		       "/tsʰ/"
"ძ"		       "/dz/"
"წ"		       "/tsʼ/"
"ჭ"		       "/tʃʼ/"
"ხ"		       "/x/"
"ჯ"	         "/dʒ/"
"ჰ"		        "/h/"
'), TRUE)

kable(alphabet, align = 'c') %>%
  kable_styling("bordered")
```

# Lenition Rules

* /v/ becomes a glide [w] following consonants and in coda positions [@hewitt1995, p. 21].
* /q/ is often pronounced with frication (ibid.).

# References
