---
title: "Palauan"
author: "Bill Mizgerd"
bibliography: pau.bib
output: html_document
---

Last Updated: 2019-07-22

# Background

**Language Family**: Austronesian / Malayo-Polynesian / Palauan

# Phonology

## Consonants

### By place of articulation

Bilabial: /b/, /m/  
Alveolar: /t/, /d/, /s/, /ɾ/, /r/, /l/  
Velar: /k/, /ŋ/  
Glottal: /ʔ/  

### By manner of articulation

Stops: /b/, /t/, /d/, /k/, /ʔ/  
Nasals: /m/, /ŋ/  
Fricatives: /s/  
Taps: /ɾ/  
Trills: /r/  
Approximants: /l/  

## Vowels

Vowels: /i/, /u/, /ɛ/, /ə/, /o/, /a/  

/ə/ only appears in unstressed syllables, and consequently, it is not universally considered to be phonemic in Palauan [@PauJosephs1975, p. 22]. For this reason, my ruleset will include /ə/ where the orthography unambiguously identifies it (i.e. with <ȩ>), but will not account for /ə/ otherwise.

Vowel length is contrastive for non-central vowels. Long front vowels glide into [j], while long back vowels glide into [w]. [@PauJosephs1975, pp. 25-26]

# Alphabet

a - /a/  
b - /b/  
ch - /ʔ/  
d - /d/  
e - /ɛ/  
ȩ - /ə/  
i - /i/  
k - /k/  
l - /l/  
ll - /lː/  
m - /m/  
n - /n/ (only in loanwords)  
ng - /ŋ/  
o - /o/  
r - /ɾ/  
rr - /r/  
s - /s/  
t - /t/  
u - /u/  

Long vowels are represented by doubling the vowel character.

# Lenition Rules

* Word-initial /d/ spirantizes to [ð], particularly in careful speech. [@PauJosephs1975, p. 8]
* Intervocalic and word-final /d/ spirantize to [ð]. [@PauJosephs1975, p. 9]
* /k/ voices to [ɡ] intervocalically. [@PauJosephs1975, p. 10]

# Misc. Rules

* When adjacent to another consonant - except /l/ - /b/ devoices to [p]. [@PauJosephs1975, p. 6]
* Word-final voiceless stops aspirate. [@PauJosephs1975, pp. 7, 10]
* Word-initial preconsonantal /d/ devoices to [t]; this rule can also co-occur with the spirantization rule mentioned above, resulting in [θ]. [@PauJosephs1975, p. 9]
* Epenthesis of [ʔ] occurs at the beginning of vowel-initial utterances. [@PauJosephs1975, pp. 11-12]
* /ŋ/ assimilates to the place of subsequent alveolar consonants. [@PauJosephs1975, p. 13]
* Word-initial preconsonantal sonorants are syllabic, except in the word <mlai>. [@PauJosephs1975, pp. 17-18]
* Epenthesis of [ə] occurs after word-final consonant clusters. [@PauJosephs1975, p. 24]
* In vowel clusters, unstressed vowels turn to glides in various contexts. [@PauJosephs1975, pp. 27-28]

# References
