---
title: "Llocano"
author: "Emily Strand"
bibliography: ilo.bib
output: html_document
---

Last Updated: 2019-07-31

# Background

**Language Family**: Austronesian / Malayo-Polynesian / Northern Luzon

Also known as Iloko.

The northern dialect is represented below.

# Phonology

## Consonants

* /h/ appears in only one native word "haán," but it is not recognized as a phoneme in the inventory [@yamamoto_phonological_2017, pg. 23].

### By manner of articulation

Labial: /p/, /b/, /m/    
Dental: /t/, /d/, /n/      
Alveolar: /s/, /ɾ/, /l/     
Palatal: /j/      
Velar: /k/, /g/, /ŋ/, /w/     
Glottal: /ʔ/     

### By place of articulation

Stops: /p/, /b/, /t/, /d/, /k/, /g/, /ʔ/   
Nasals: /m/, /n/, /ŋ/   
Fricatives: /s/     
Laterals: /l/    
Tap: /ɾ/     
Glides: /w/, /j/        


## Vowels

* Although /o/ was historically recognized as an allophone of /u/, it is now considered a phoneme due to the adoption of several Spanish loanwords [@rubino_ilocano_2000, pg. xxviii].
* There is some debate as to how many dipthongs are present in Ilocano. @constantino_ilokano_1971 specifies 14 (pg. 6), while @rubino_ilocano:_1998 specifies 5 (pg. xxix). On the other hand, @yamamoto_phonological_2017 argues that such combinations actually represent sequences of consonants and vowels rather than dipthongs (pg. 32). Due to a lack of consensus, I will not account for them.

Vowels: /i/, /ɛ/, /a/, /u/, /o/

# Alphabet

a - /a/     
b - /b/           
d - /d/     
e - /ɛ/             
g - /g/          
i - /i/       
k - /k/        
l - /l/      
m - /m/           
n - /n/        
ng - /ŋ/       
o - /o/      
p - /p/        
r - /ɾ/         
s - /s/           
t - /t/          
u - /u/        
w - /w/         
y - /j/      
(-) - /ʔ/       

# Stress

* Although stress is phonemic in Ilocano, @rubino_ilocano_2000 argues that it only differentiates meaning in very few words (pg.xxix).

# Lenition Rules

* /k/ and /t/ sometimes debuccalizes to /ʔ/ preceding consonants [@rubino_ilocano_2000, pg.xxiv]    
* /k/ often spirantizes intervocalically [@rubino_ilocano_2000, pg. xxiv].
* /t/,/d/, and /s/ palatalize to /tʃ/, /dʒ/, and /ʃ/ respectively preceding /j/ or /i/ [@rubino_ilocano_2000, pg.xxvii]. /t/ also palatalizes to /tʃ/ in borrowed words [@rubino_ilocano_2000, pg. xxv].   

# Misc Rules

* Glottal stops occur preceding word initial vowels [@rubino_ilocano:_1998, pg.12].       
* Glottal stops occur intervocalically (except with ia, ie, iu, and ua) [@rubino_ilocano:_1998, pg. 12].      
* Gemination can occur with every consonant except /ʔ/ and/h/ [@rubino_ilocano_2000, pg. xxv, xxxiv].        
* /u/ is sometimes realized as /o/ word finally [@constantino_ilokano_1971, pg. 4]
