---
title: "Shilha"
author: "Bill Mizgerd"
bibliography: shi.bib
output: html_document
---

Last Updated: 2019-07-09

# Background

**Language Family**: Afro-Asiatic / Berber / Northern Berber / Atlas / Shilha

The name of the language is spelled in a variety of ways, including Shilha, Tashelheet, and Tachelhit.

# Phonology

## Consonants

* All Shilha consonants can be geminated. [@ShiRidouane2008, p. 323]
* @ShiApplegate1958 argues for the labialized consonants as allophones that occur before /u/, although he also describes them as having relatively free variation. (pp. 2-3)
* @ShiKossmann1996 argues for the absence of /nˤ/ and /ʒˤ/. (p. 467)
* @ShiKossmann1996 argues for velar rather than uvular fricatives. (ibid.)
* @ShiKossmann1996 states that no minimal pairs exist between labialized consonants and their non-labialized counterparts (p. 468). I will include labialized in my ruleset only if they are orthographically marked.

### By place of articulation

Labial: /b/, /m/, /f/, /w/  
Alveolar: /t/, /d/, /n/, /s/, /z/, /r/, /l/  
Alv. (pharyngealized): /tˤ/, /dˤ/, /nˤ/, /sˤ/, /zˤ/, /rˤ/, /lˤ/  
Postalveolar: /ʃ/, /ʒ/, /ʒˤ/  
Palatal: /j/  
Velar: /k/, /kʷ/, /ɡ/, /ɡʷ/  
Uvular: /q/, /qʷ/, /χ/, /χʷ/, /ʁ/, /ʁʷ/  
Pharyngeal: /ħ/, /ʕ/  
Glottal: /h/  

### By manner of articulation

Stops: /b/, /t/, /tˤ/, /d/, /dˤ/, /k/, /kʷ/, /ɡ/, /ɡʷ/, /q/, /qʷ/  
Nasals: /m/, /n/, /nˤ/  
Fricatives: /f/, /s/, /sˤ/, /z/, /zˤ/, /ʃ/, /ʒ/, /ʒˤ/, /χ/, /χʷ/, /ʁ/, /ʁʷ/, /ħ/, /ʕ/, /h/  
Trills: /r/, /rˤ/  
Approximants: /w/, /l/, /lˤ/, /j/  

## Vowels

Vowels: /i/, /u/, /a/  

* [ə] is added through epenthesis in some contexts, but is not a phoneme in its own right. [@ShiKossmann1996, p. 468]
* There are no diphthongs or vowel clusters in Shilha. [@ShiKossmann1996, p. 463]
* @ShiApplegate1958 attests two tonal contours, but does not appear to find them contrastive. (p. 6)

# Alphabet

a - /a/   
b - /b/  
d - /d/  
ḍ - /dˤ/  
e - [ə] (<e> will go to null in the ruleset, due to [ə]'s non-phonemic status in Shilha)  
ɛ - /ʕ/  
f - /f/  
g - /ɡ/  
ġ - /ʁ/  
h - /h/  
ḥ - /ħ/  
h̬ - /χ/ (in some orthographies)  
i - /i/  
j - /ʒ/  
j̣ - /ʒˤ/  
k - /k/  
l - /l/  
ḷ - /lˤ/  
m - /m/  
n - /n/  
ṇ - /nˤ/  
q - /q/  
r - /r/  
ṛ - /rˤ/  
s - /s/  
ṣ - /sˤ/  
š - /ʃ/  
t - /t/  
ṭ - /tˤ/  
u - /u/  
w - /w/  
ʷ - marks labialization of preceding consonant  
x - /χ/ (in some orthographies)  
y - /j/  
z - /z/  
ẓ - /zˤ/  

# Lenition Rules

* Some dialects spirantize bilabial and velar stops; other dialects spirantize the alveolar stops. [@ShiRidouane2008, p. 323]

# Misc. Rules

* Epenthetic [ə] occurs interconsonantally, except in VCCV or #CCV sequences, where adding [ə] would yield an open syllable. [@ShiKossmann1996, p. 463]
  * Where there exist more than two consecutive consonants, epenthesis first occurs between the final two consonants in the cluster, and proceeds backwards, adding [ə] in any permissible positions. For instance, the word /iʃrz/ becomes [iʃrəz] rather than \*[iʃərəz] or \*[iʃərz]. (ibid.)
* A few consonants undergo fortition when they lengthen. /dː/ devoices to [tː], /ʁː/ despirantizes and devoices to [qː], and /wː/ deapproximantizes to [ɡʷː]. [@ShiKossmann1996, p. 465]

# References
