---
title: "Catalan"
author: "Abi Creighton"
bibliography: ca.bib
output: html_document
---
#Background

**Language family**: Indo-European / Italic / Romance / Western / Gallo-Romance / Occitano-Romance / Catalan / Central Catalan dialect


Central Catalan

# Phonology

## Consonants

### By place of articulation

Bilabial: /p/, /b/, /m/
Labiodental: /f/
Alveolar: /t/, /d/, /s/, /z/, /ts/, /dz/, /n/, /l/, /r/, /ɾ/
Palatal: /ʃ/, /ʒ/, /tʃ/, /dʒ/, /ɲ/, /ʎ/, /j/
Velar: /k/, /g/, /ŋ/, /w/

### By manner of articulation
Stop: /p/, /b/, /t/, /d/, /k/, /g/
Nasal: /m/, /n/, /ɲ/, /ŋ/
Affricate: /ts/, /dz/, /tʃ/, /dʒ/
Fricative: /f/, /s/, /z/, /ʃ/, /ʒ/
Approximant: /j/, /w/, /l/, /ʎ/
Tap: /ɾ/
Trill: /r/

## Vowels

/a/, /ɛ/, /e/, /i/, /ɔ/, /o/, /u/

# Alphabet

* Whether <v> transcribes to /b/ or /v/ is a dialectal difference. I opted for /b/ due to it being more reflective of the standardized language.
* k and w are used in loanwords.

a - /a/
à - /a/
b - /b/
c - /k/ or /s/ (preceding front vowels)
ç - /s/
d - /d/
e - /e/ or /ɛ/ (stressed)
è - /ɛ/
é - /e/
f - /f/
g - /g/ (preceding front vowels); /ʒ/ (preceding back vowels)
h - null
i - /i/
í - /i/
ï - /i/
j - /ʒ/
k - /k/ (only appears in loanwords)
l - /l/
ll - /ʎ/
ŀl - /lː/
m - /m/
n - /n/
o - /ɔ/ or /o/(stressed) or /u/(unstressed)
ò - /ɔ/
ó - /o/
p - /p/
q - /k/
r - /ɾ/ or /r/ (word-initially)
s - /s/
t - /t/
u - /u/
ú - /u/
ü - /u/
v - /b/
w - /w/ (only used in loan words)
x - /ʃ/
y - /j/ (only in loan words)
z - /z/

# Digraphs

gu - /g/ (preceding front vowels); /gw/ (preceding back vowels)
gü - /gw/ (preceding front vowels)
ig - /tʃ/ (syllable-finally)
ix - /ʃ/ (syllable-finally)
qu - /k/ (preceding front vowels); /kw/ (preceding back vowels)
qü - /kw/ (preceding front vowels)
ss - /s/
ny - /ɲ/
tg - /dʒ/ (preceding front vowels)
tj - /dʒ/
tx - /tʃ/
rr - /r/
ts - /ts/
tz - /dz/

#Rules
/g/ --> [tʃ] / i_
/l/ --> [ʎ] / l_
/n/ --> [ɲ] / _ /j/

##Lenition

###Spirantization
/k/ --> [s] / _V[+front +tense]
/g/ --> [ʒ]/ _V[+front +tense]

###Deletion
C[+obstruent α place] --> ∅ / C[α place]_#
/r/ --> ? / _#

/s/ becomes voiced intervocalically
