---
title: "Tagalog"
author: "Abi Creighton"
bibliography: tl.bib
output: html_document
---
#Background
**Language family**: Austronesian / Philippine / Central Philippine / Tagalog

Tagalog borrows extensively from other languages, primarily Spanish. While some of these borrowings are adapted to fit Tagalog orthography, some keep their native spelling and pronunciations and as such are difficult to account for in the rules. For example, Spanish /j/ and /r/ are pronounced [h] and [r] respectively, while /j/ and /r/ in native Tagalog words are [dʒ] and [ɾ]. The rules focus on the pronunciation of native Tagalog words, not loanwords.

#Phonology

##Consonants
###Consonants by place
Bilabial: /m/, /p/, /b/
Dental: /n̪/, /t̪/, /d̪/
Alveolar: /ts/, /s/, /l/, /ɾ/
Post-alveolar/Palatal: /ɲ/, /tʃ/, /dʒ/, /ʃ/, /j/
Velar: /ŋ/, /k/, /g/, /x/, /w/
Glottal: /ʔ/, /h/
  
###Consonants by manner
Nasal: /m/, /n/, /ɲ/, /ŋ/
Stop: /p/, /b/, /t/, /d/, /k/, /g/, /ʔ/
Affricate: /ts/, /tʃ/, /dʒ /
Fricative: /s/, /ʃ/, /x/, /h/
Approximant: /l/, /j/, /w/
Rhotic: /ɾ/
 
##Vowels
Front close: /i/
Front mid: /ɛ/
Central open: /a/
Back close: /u/
Back mid: /o̞/

  
#Alphabet
A, a: /a/
B, b: /b/
C, c: /k/ or /s/ (only in loanwords)
D,d: /d/
E, e: /ɛ/
F, f: /f/ (only in loanwords)
G, g: /g/
H, h: /h/
I, i: /i/
J, j: /dʒ/ or /h/ (only in loanwords)
K,k: /k/
L, l: /l/
M, m: /m/
N, m: /n/
Ñ, ñ: /É²/ (only in loanwords)
Ng, ng: /ɲ/
O, o: /o̞/
P, p: /p/
Q, q: /k/ (only in loanwords)
R, r: /ɾ/
S, s: /s/
T, t: /t/
U, u: /u/
V, v: /v/ (only in loanwords)
W, w: /w/
X, x: /ks/ (only in loanwords)
Y, y: /j/
Z, z: /z/ (only in loanwords)

#Rules: 
/k/ > [kx]/#_ (in the Manila dialect)
/a/ > [ɐ] in unstressed positions
/i/ > [ɪ] in unstressed positions
/u/ > [ʊ] in unstressed positions
/i/ > ∅/sC_
Lenition of velar stops: 
/k/ > [x]/V_V
/g/ > [ɰ]/V_V
  