---
title: "South Tairora"
author: "Bill Mizgerd"
bibliography: omw.bib
output: html_document
---

Last Updated: 2019-07-19

# Background

**Language Family**: Trans-New Guinea / Kainantu-Goroka / Kainantu / Tairora / South Tairora

# Phonology

## Consonants

* /ᵐp/ and /ⁿt/ can be realized with voicing in the Suwaira dialect. [@OmwLVincent2010, p. 578]
* The contrast between /s/ and /h/ is minor, and is most clearly realized in loanwords. [@OmwLVincent2010, p. v]
* The palatalized consonants only occur in some dialects. [@OmwAVincent2003, p. 1]

### By place of articulation

Bilabial: /p/, /ᵐp/, /m/, /β/, /β̃/  
Alveolar: /t/, /ⁿt/, /tʲ/, /ⁿtʲ/, /n/, /nʲ/, /s/, /ɾ/, /ɾ̃/  
Velar: /k/, /ᵑk/, /kʲ/  
Glottal: /ʔ/, /h/  

### By manner of articulation

Stops: /p/, /ᵐp/, /t/, /ⁿt/, /tʲ/, /ⁿtʲ/, /k/, /ᵑk/, /kʲ/, /ʔ/  
Nasals: /m/, /n/, /nʲ/  
Fricatives: /β/, /s/, /h/  
Flaps: /ɾ/, /ɾ̃/  

## Vowels

Short: /i/, /ɘ/, /u/  
Long: /ɛː/, /aː/, /ɔː/  
Diphthongs: /ɘj/, /ɘw/  

The transcription of the diphthongs is somewhat speculative, because all the sources I have found describe the diphthongs by analogy to English rather than in IPA terms. Both sources compare <au> to the first vowel in "over"; for <ai>, @OmwAVincent2003 compares it to the first vowel in "iron", while @OmwLVincent2010 describes it as between that vowel and the vowel in "may."

Depending on the dialect of English, the vowel in "over" can be either /oʊ/ or /əʊ/; I preferred the second pronunciation for <au>, because /o/ is not present in any dialect of Tairora. Then, I preferred the analysis of @OmwLVincent2010 for <ai>; I chose /ɘɪ/ as a compromise between the /aɪ/ of "iron" and the /eɪ/ of "may", which had the additional benefit of paralleling with the other /ɘ/-initial Tairora diphthong. This interpretation also maps neatly onto the orthography, since a standalone <a> in Tairora represents /ɘ/.

Finally, I opted for /ɘj/ and /ɘw/ rather than /ɘɪ/ or /ɘʊ/, because @OmwLVincent2010 describes <ai> and <au> as "glides" (p. vi).

# Alphabet

a - /ɘ/  
  ai - /ɘj/  
  au - /ɘw/  
aa - /aː/  
e - /ɛː/  
h - /h/  
i - /i/  
k - /k/  
  ky - /kʲ/  
m - /m/  
  mp - /ᵐp/  
  mw - /β̃/  
n - /n/  
  nk - /ᵑk/  
    nky - /ᵑkʲ/  
  nr - /ɾ̃/  
  nt - /ⁿt/  
    nty - /ⁿtʲ/  
  ny - /nʲ/  
o - /ɔː/  
p - /p/  
q - /ʔ/  
r - /ɾ/  
s - /s/  
t - /t/  
  ty - /tʲ/  
u - /u/  
v - /β/  

# Lenition Rules

* Prenasalization is often omitted in the Suwaira dialect. [@OmwLVincent2010, p. 578]

# Misc. Rules

* Word-initial /β/ is realized as [b]. [@OmwLVincent2010, p. 578]

# References
