---
title: "Asturian"
author: "Emily Strand"
bibliography: ast.bib
output: html_document
---

Last updated: 2019-08-28

# Background

**Language family**: Indo-European / Italic / Romance / Western / West Ibero-Romance / Asturo-Leonese

# Phonology

## Consonants

### By place of articulation

Bilabial: /p/, /b/, /m/  
Labio-dental: /f/  
Dental: /t/, /d/, /θ/  
Alveolar: /n/, /r/, /ɾ/, /s/, /l/  
Post-alveolar: /ʃ/  
Palatal: /tʃ/, /ɲ/, /ʎ/, /ʝ/  
Velar: /k/, /g/  

### By manner of articulation

Stops: /p/, /b/, /t/, /d/, /k/, /g/  
Affricates: /tʃ/  
Nasals: /m/, /n/, /ɲ/  
Trills: /r/  
Tap: /ɾ/  
Fricative: /f/, /θ/, /s/, /ʃ/, /ʝ/  
Lateral Approximant: /l/, /ʎ/  

## Vowels

* /i/ and /u/ become glides [j] and [w] respectively, when unstressed, forming dipthongs and triphthongs with adjoining vowels [@muniz-cachon_asturian_2018, pg. 6].

Front: /i/, /e/  
Back: /u/, /o/, /a/    

# Alphabet

* In some dialects the digraphs ⟨ḷḷ⟩, ⟨ḥ⟩, ⟨ts⟩, ⟨yy⟩ appear, corresponding to a variety of different phonemes [@academia_de_la_llingua_asturiana_gramatica_2001, pg. 15].  
* ⟨j⟩, ⟨k⟩, and ⟨w⟩ appear in loanwords [@academia_de_la_llingua_asturiana_gramatica_2001, pg. 15].   

a - /a/  
b - /b/  
c - /k/ (preceding back vowels); /θ/ (preceding front vowels)  
  ch - /tʃ/  
d - /d/  
e - /e/  
f - /f/  
g - /g/  
  gu - /g/ (preceding front vowels)  
h - ∅  
i - /i/  
l - /l/  
  ll - /ʎ/  
m - /m/  
n - /n/  
ñ - /ɲ/  
o - /o/  
p - /p/  
qu - /k/ (preceding front vowels)
r - /r/ or /ɾ/  
  rr - /r/  
s - /s/  
t - /t/  
u - /u/  
  ü - /u/  
v - /b/  
x - /ʃ/  
y - /ʝ/  
z - /θ/  

# Stress

* Primary stress is indicated by an accented vowel [@academia_de_la_llingua_asturiana_gramatica_2001, pg. 18].  

# Lenition Rules

* Fricatives /θ/, /s/, /ʃ/ and tend to become voiced in coda positions [@academia_de_la_llingua_asturiana_gramatica_2001, pg. 39-40].  
* /d/ spirantizes intervocalically and followed by /r/ [@academia_de_la_llingua_asturiana_gramatica_2001, pg. 38].  
* /b/, /d/, /g/ become approximates word-medially, following obstruents [@muniz-cachon_asturian_2018, pg. 3].    
* In addition to approximating, /g/ often spirantizes to /ɣ/ [@muiz-cachon_asturian_2018, pg. 3].  


# Misc Rules

* An apostrophe indicates a sound is missing - synonymous with a contraction [@academia_de_la_llingua_asturiana_gramatica_2001, pg. 18].  
* Dashes are used to separate sounds that would otherwise be altered due to specified digraphs (retention of pronouns) [@academia_de_la_llingua_asturiana_gramatica_2001, pg. 18].  
* /r/ and /ɾ/ are contrastive word - medially. Otherwise, /r/ occurs word initially and /ɾ/ occurs word finally [@muniz-cachon_asturian_2018, pg. 3].  
