---
title: "Nomatsiguenga"
author: "Emily Strand"
bibliography: not.bib
output: html_document
---

Last updated: 2019-10-01

# Background

**Language family**: Arawakan / Maipuran / Southern / Campa

# Phonology

## Consonants

* There is mention of a placeless /N/ phoneme that occurs in final syllables word-medially, preceding a stop consonant [@Chen2019, pg. 3; @Lawrence2013, pg. 8, 9]. Both such sources also indicate /m/ and /n/ as phonemes of Nomatsiguenga; however, it is said to behave differently in such a way where it deletes preceding vowels [@Chen2019, pg. 3]. Orthographically, /N/ is represented "as an ⟨m⟩ before bilabials and ⟨n⟩ elsewhere" [@Lawrence2013, pg. 8] therefore, due to this conflation of /N/ with /n/ and /m/ I will include /N/ in the phonemic inventory but it won't be represented in the rules.

### By place of articulation

Bilabial: /p/, /b/, /m/  
Alveolar: /t/, /n/, /s/, /ts/  
Alveo-palatal: /ʃ/, /tʃ/, /ɾ/, /j/  
Velar: /ŋ/, /k/, /g/  
Glottal: /h/  
Unspecified: /N/  

### By manner of articulation

Stop: /p/, /b/, /t/, /k/, /g/  
Nasal: /m/, /n/, /ŋ/, /N/  
Fricative: /s/, /ʃ/, /h/  
Affricate: /ts/, /tʃ/  
Flap: /ɾ/  
Approximant: /j/  

## Vowels

* Tone is contrastive in Nomatsiguenga (high tone vs. no tone). High tone is marked over the vowel with an acute accent, whereas no tone is unmarked [@Chen2019, pg. 68; @Lawrence2013, pg. 15].
* Length is phonemic in Nomatsiguenga. Long vowels are indicated by the duplication of vowels (either one is marked with a high tone) (ibid.).
* /ɨ/ does not have a long counterpart [@Lawrence2013, pg. 8].

/i/, /ɨ/, /e/, /a/, /o/  

Diphthongs: /ai/, /ei/, /oi/  

# Alphabet

a - /a/  
b - /b/  
c - /k/  
e - /e/  
ë - /ɨ/  
g - /g/  
i - /i/  
j - /h/  
m - /m/  
n - /n/ or /ŋ/ (preceding <c> or <qu>)  
o - /o/  
p - /p/  
q - /k/  
r - /ɾ/  
s - /s/  
t - /t/  
u - /u/  
y - /j/  

## Multigraphs

ch - /tʃ/  
ng - /ŋ/  
sh - /ʃ/  
ts - /ts/  
gu - /g/  
ngu - /ŋ/  
qu - /k/  


# Lenition Rules

* /k/ and /p/ tend to become voiced within a root with the addition of prefixes [@Chen2019, pg. 27, 28].
* /h/ may delete preceding a vowel marked with high tone [@Lawrence2013, pg. 20].
* Stops at the morpheme boundary are realized as /h/ preceding a suffix-onset /k/ [@Lawrence2013, pg. 20, 21].  

# Misc Rules

* /q/ is palatalized preceding front vowels (spelled by ⟨qu⟩) [@Chen2019, pg. 13].
