---
title: "Jamaican Creole"
author: "Justin Bai"
bibliography: jam.bib
output: html_document
---
# Background
**Language family**: English creole

As stated by @harry2006jamaican, "Jamaican Creole is one of the major Atlantic
English-lexifier creoles spoken in the Caribbean." Though one may consider a
continuum between Jamaican Creole and Jamaican English, the form considered
here is after @harry2006jamaican, which is "basilectal Jamaican Creole and
radically different phonologically from the acrolectal form, Jamaican English,
a regionally distinctive dialect of English."

# Alphabet
## Consonants
* ⟨b⟩ = /b/
* ⟨d⟩ = /d/
* ⟨ch⟩ = /tʃ/
* ⟨f⟩ = /f/
* ⟨g⟩ = /g/
* ⟨h⟩ = /h/
* ⟨j⟩ = /dʒ/
* ⟨k⟩ = /k/
* ⟨l⟩ = /l/
* ⟨m⟩ = /m/
* ⟨n⟩ = /n/
* ⟨ng⟩ = /ŋ/
* ⟨p⟩ = /p/
* ⟨r⟩ = /ɹ/
* ⟨s⟩ = /s/
* ⟨sh⟩ = /ʃ/
* ⟨t⟩ = /t/
* ⟨v⟩ = /v/
* ⟨w⟩ = /w/
* ⟨y⟩ = /j/
* ⟨z⟩ = /z/

## Vowels
Jamaican Creole has long and short vowels. The short
vowels are:
* ⟨a⟩ = /a/
* ⟨e⟩ = /e/
* ⟨i⟩ = /i/
* ⟨o⟩ = /o/
* ⟨u⟩ = /u/

The long vowels are:
* ⟨aa⟩ = /aa/
* ⟨ii⟩ = /ii/
* ⟨uu⟩ = /uu/

Jamaican Creole has diphthongs. The only diphthong that is not transparent orthographically is /au/,
which is spelled ⟨ou⟩.

# Phonology
## Consonants
There is some debate about the status of /h/ in
Jamaican Creole. It appears that "[h] may be phonetic in Eastern varieties" but "is phonemic in the Western varieties" (@harry2006jamaican).
## Vowels
According to @harry2006jamaican, "The long vowels are represented phonemically as a sequence of short vowels."
