---
title: "Iduna"
author: "Bill Mizgerd"
bibliography: viv.bib
output: html_document
---

Last Updated: 2019-07-15

# Background

**Language Family**: Austronesian / Malayo-Polynesian / Eastern Malayo-Polynesian / Oceanic / Western Oceanic / Papuan Tip / Nuclear Papuan Tip / North Papuan Mainland-D'Entrecasteaux / Bwaidoga / Iduna

The language is also known as Vivigani.

# Phonology

## Consonants

* [p] occurs in free variation with /b/. [@VivSampson1965, p. 10]

### By place of articulation

Labial: /b/, /m/, /f/, /v/, /w/  
Alveolar: /t/, /d/, /n/, /l/  
Palatal: /j/  
Velar: /k/, /ɡ/  
Glottal: /ʔ/, /h/  

### By manner of articulation

Stops: /b/, /t/, /d/, /k/, /ɡ/, /ʔ/  
Nasals: /m/, /n/  
Fricatives: /f/, /v/, /h/  
Approximants: /w/, /l/, /j/  

## Vowels

Vowels: /i/, /u/, /e/, /o/, /ɑ/  

@VivSampson1965 argues for /a/ rather than /ɑ/. (p. 21)

# Alphabet

a - /ɑ/  
b - /b/  
d - /d/  
e - /e/  
f - /f/  
g - /ɡ/  
h - /h/  
i - /i/  
k - /k/  
l - /l/  
m - /m/  
n - /n/  
o - /o/  
s - /t/ (spirantized allophone)  
t - /t/  
u - /u/  
v - /v/  
w - /u/ (in C_V position)  
w - /w/ (elsewhere)  
y - /j/  
' - /ʔ/  

/u/ (rather than /w/) is held to be the underlying phoneme for consonant labialization, because Iduna disallows consonant clusters. [@VivSampson1965, p. 30] [@VivLucht1992, p. 3]

# Lenition Rules

* /t/ spirantizes to [s] before front vowels. [@VivLucht1992, p. 3] [@VivSampson1965, p. 9]
* Word-medial /ɡ/ spirantizes to [ɣ]. (ibid.)
* In C_V contexts, /u/ is realized as simply a labialization of the preceding consonant. [@VivSampson1965, p. 6]

# Misc. Rules

* Phrase-final /d/ devoices and aspirates, yielding [tʰ]. [@VivLucht1992, p. 3]
* /u/ nasalizes after /m/. [@VivSampson1965, p. 20]
* Unstressed /ɑ/ raises to [ʌ]. [@VivSampson1965, p. 21]

# References
