---
title: "Huichol"
author: "Emily Strand"
bib: hch.bib
output: html_document
---

Last updated: 2019-09-26

# Background

**Language family**: Uto-Aztecan / Southern / Sonoran / Corachol

# Phonology

* Although varying tones are found in Huichol [@grimes_huichol_1959], whether they are contrastive or not is rather unclear [@banerji_huichol_2014, pg. 15]. @banerji_huichol_2014 explains that they are most likely not contrastive, but rather different phonological realizations (pg. 18).

## Consonants

* There is not a voicing contrast in Huichol [@bierge_clause_2017, pg. 39].

### By place of articulation

Bilabial: /p/, /m/, /w/  
Alveolar: /t/, /ts/, /r/, /ɾ/, /n/  
Palatal: /j/  
Velar: /k/, /kʷ/  
Glottal: /ʔ/, /h/  

### By manner of articulation  

Stop: /p/, /t/, /k/, /kʷ/, /ʔ/  
Affricate: /ts/  
Fricative: /h/  
Trill: /r/  
Flap: /ɾ/  
Nasal: /m/, /n/  
Approximant: /w/, /j/  

## Vowels

* Although very few minimal pairs exist, vowel length is contrastive [@bierge_clause_2017, pg. 36]. Long vowels are indicated by repeated graphemes.
* 13 diphthongs can be found in the Huichol language [@leza_gramatica_1999, as cited in @bierge_clause_2017, pg. 37, 38].

/i/, /e/, /a/, /u/, /ɨ/  

Diphthongs: /ai/, /au/, /aɨ/, /ua/, /ui/, /ei/, /eɨ/, /eu/, /ie/, /iɨ/, /iu/, /ɨi/, /ɨa/  

# Alphabet

* There have been several accounts concerning the Huichol orthography. The orthography immediately below represents that of the Departamento de Lenguas Indígenas (DELI) [@leza_gramatica_1999, as cited in @bierge_clause_2017, pg. 44, 45]. Immediately following, I have also included the different orthagraphic variations.

a - /a/  
e - /e/  
h - /h/  
i - /i/  
ɨ - /ɨ/  
k - /k/  
m - /m/  
n - /n/  
p - /p/  
r - /ɾ/  
t - /t/  
u - /u/  
w - /w/  
x - /r/  
y - /j/  
’ - /ʔ/  

## Digraphs

kw - /kʷ/  
ts - /ts/  

## Orthographic Variations

* Most of the variations were indicated by @leza_gramatica_1999, following either the Secretaría de Educación Pública (SEP) or the Summer Institute of Linguistics (SIL) (as cited in @bierge_clause_2017, pg. 44, 45).

qu; c - /k/   (SIL)  
ku - /kʷ/     (SEP)  
cu - /kʷ/     (SIL)  
s - /ts/      (SIL)  
tz - /ts/     (SEP)  
xr; rr - /r/  (SEP)  
j - /h/       (SEP)  
v - /w/       (SIL)  
ü - /ɨ/       [@haugen_kill_2015]  

# Syllable Structure

* The syllable structures permitted in Huichol follow the order of CV(V) [@banerji_huichol_2014, pg. 6].
* Complex consonant clusters are not permitted (ibid.).

# Lenition Rules

* /p/ and /k/ can become voiced intervocalically [@leza_gramatica_1999, as cited in @bierge_clause_2017, pg. 42].
* /h/ is frequently deleted word-initially [@mcintosh_huichol_1945, pg. 31].
* /r/ often alternates with [l] [@mcintosh_huichol_1945, pg. 32].
* /w/ fricates to [β] preceding high-central and mid-front vowels [@mcintosh_huichol_1945, pg. 32].
* /k/ is palatalized preceding /e/ [@mcintosh_huichol_1945, pg. 31].
* /ts/ changes to /s/ preceding a consonant [@mcintosh_huichol_1945, pg. 31].


# Misc Rules

* /e/ is realized as [ɛ] preceding /k/ [@bierge_clause_2017, pg. 38].
* /u/ and /o/ often alternate with [o] (ibid.).


* Although stress is indicated orthographically by a grave accent over the vowel [@bierge_clause_2017, pg. 37], it doesn't appear to be marked in the Crubadan corpus, thus no rules will be written to account for such a diacritic.
