---
title: "Chichewa"
author: "Maddie Critz"
date: "December 3, 2018"
output: html_document
---
#Background
  **Language Family** : Niger-Congo / Atlantic-Congo / Bennue-Congo / Southern Bantoid / Bantu / Nyasa / Chewa

#Phonology

     ##Consonants
          ###Stops
            /b/    
            /p/      
            /pʰ/
            /d/ 
            /t/
            /tʰ/
            /g/
            /k/
            /kʰ/
          ###Fricatives
            /v/
            /β/
            /f/
            /z/
            /s/
            /ʃ/
         ###Affricates
            /dz/
            /ts/
            /dʒ/
            /tʃ/
            /tʃʰ/
         ###Nasals
            /m/
            /n/
            /ŋ/
         ###Approximates/Semi-Vowels
            /w/
            /y/
    ###Homorganic Nasals??
  
    ##Vowels
      /a/
      /ɛ/
      /i/
      /ɔ/
      /u/
#Alphabet from Omniglot
  
  a --> [a]
  b --> [b]
  c --> [tʃ]
  d --> [d]
  e --> [ɛ]
  f --> [f]
  g --> [g]
  h --> [h] 
  i --> [i]
  j --> [dʒ]
  k --> [k]
  l --> [l]
  m --> [m]
  n --> [n]
  o --> [ɔ]
  p --> [p]
  r --> [ɽ] 
  s --> [s]
  t --> [t]
  u --> [u]
  v --> [v]
  w --> [w]
  ŵ --> [β]
  z --> [z]
  ch --> [tʃ]
  kh --> [kʰ]
  ng --> [ŋg]
  ng' --> [ŋ]
  ph --> [pʰ]
  tch --> [tʃʰ]
  th --> [tʰ]
  

  
# Lenition processes:
  
  nasal place assimilation: nasals directly preceding consonants assimilate to the POA of the consonant
  
  /m/ -> /ɱ/ / _f
  /n/ -> palatalized / _ch
  /n/ -> velarized / _(k,g)
  
  post-nasal stop aspiration
  
  /t,k,p/ -> aspirated / (nasal)_
  
  more notes:
  
  /l/ is difficult to distinguish from a rhotic sound in speech, but /l/ exists in the Chichewa orthography. Borrowed words with r use the retroflex [ɽ]
  
  Vowel lengthening is contrastive in Proto-Bantu and other languages related to Chichewa, but in Standard Chichewa, nearly all vowels present as short. However there is a very small number of minimal pairs that show contrastive vowel length.
  
  
  
  
  
  
  