---
title: "Apurinã"
author: "Emily Strand"
bib: apu.bib
output: html_document
---

Last updated: 09-11-2019

# Background

**Language family**: Arawakan / Maipuran / Southern Maipuran / Purus

# Phonology

## Consonants

* /ɲ/ and /h/ are sometimes omitted from the consonantal inventory depending on the dialect; however, given that I'm not focussing on a specific dialect, I will classify them as phonemes, just as @facundes_language_2000 does (pg. 55, 71).
* Voicing is not contrastive in Apurinã [@facundes_language_2000, pg. 70].

### By place of articulation

Bilabial: /p/, /m/
Alveolar: /t/, /n/, /ɾ/, /s/, /ts/
Paltal-alveolar: /tʃ/, /ʃ/
Palatal: /ɲ/, /j/
Velar: /k/, /ɰ/
Glottal: /h/

### By manner of articulation

Stop: /p/, /t/, /k/
Nasal: /m/, /n/, /ɲ/
Flap: /ɾ/
Fricative: /s/, /ʃ/
Affricate: /ts/, /tʃ/
Approximant: /j/, /ɰ/

## Vowels

* Vowels are contrastive in terms of length and nasality [@facundes_language_2000, pg. 55].
* Long vowels (both oral and nasal) are indicated by repeated graphemes.
* In addition to oral diphthongs, Apurinã includes nasal diphthongs, although these are very infrequent [@facundes_language_2000, pg. 85-87].

Oral (short): /i/, /e/, /a/, /ɨ/, /o/
Oral (long): /iː/, /eː/, /aː/, /ɨː/, /oː/
Nasal (short): /ĩ/, /ẽ/, /ã/, /ɨ̃/, /õ/
Nasal (long): /ĩː/, /ẽː/, /ãː/, /ɨ̃ː/, /õː/

Dipthongs (oral): /ai/, /ei/, /oi/, /ao/, /io/
Dipthongs (nasal): /ãĩ/, /ẽĩ/, /ãõ/, /õĩ/

# Alphabet

a - /a/
ã - /ã/
e - /e/
ẽ - /ẽ/
h - /h/
i - /i/
ĩ - /ĩ/
k - /k/
m - /m/
n - /n/
o - /o/
õ - /õ/
p - /p/
r - /ɾ/
s - /s/
t - /t/
u - /ɨ/
ũ - /ɨ̃/
w - /ɰ/
x - /ʃ/
y - /j/

## Digraphs

nh - /ɲ/
ts - /ts/
tx - /tʃ/

# Syllable Structure

* The possible syllable structures include [@facundes_language_2000, pg. 87-88]:

    CV
    CVV
    VV
    V

* Based on this, it would seem that Apurinã does not allow complex onsets and consonant clusters. They also seem to require empty codas.

# Lenition Rules

* Voiceless stops can become voiced following nasal vowels [@facundes_language_2000, pg. 73].
* /h/ deletes when followed by a vowel [@facundes_language_2000, pg. 83].

# Misc Rules

* Vowels are often devoiced word-finally in unstressed positions [@facundes_language_2000, pg.].
* There is free variation of oral and nasal vowels preceding nasal consonants (the contrast is neutralized) [@facundes_language_2000, pg. 64].
* Vowels preceding nasal vowels become nasal [@facundes_language_2000, pg. 66].
* /k/ palatalizes when preceding [ɛ], which is an allophone of /e/ [@facundes_language_2000, pg. 78].
* Aspiration of stops occurs preceding devoiced vowels in unstressed positions [@facundes_language_2000, pg. 78-79].
* /n/ palatalizes preceding /i/ [@facundes_language_2000, pg. 82].
* Apostrophes indicate vowel omission [@104611 , pg. 3].
