---
title: "Yucatec Maya"
author: "Justin Bai"
bibliography: yua.bib
output: html_document
---
# Background
**Language family**: Mayan

# Alphabet
Yucatec Maya (YM) is written using the Latin alphabet with some modifications to represent ejectives and the glottal stop.

## Consonants
* ⟨b⟩ = /ɓ/
* ⟨ch⟩ = /tʃʰ/
* ⟨chʼ⟩ = /tʃʼ/
* ⟨j⟩ = /h/
* ⟨k⟩ = /kʰ/
* ⟨kʼ⟩ = /kʼ/
* ⟨l⟩ = /l/
* ⟨m⟩ = /m/
* ⟨n⟩ = /n/
* ⟨p⟩ = /pʰ/
* ⟨pʼ⟩ = /pʼ/
* ⟨r⟩ = /ɾ/  
* ⟨s⟩ = /s/  
* ⟨t⟩ = /tʰ/  
* ⟨tʼ⟩ = /tʼ/  
* ⟨tz⟩ = /tsʰ/  
* ⟨tzʼ⟩ = /tsʼ/  
* ⟨x⟩ = /ʃ/  
* ⟨w⟩ = /w/  
* ⟨y⟩ = /j/  
* ⟨ʼ⟩ = /ʔ/  

## Vowels
YM has short vowels and long vowels.
The short vowels are shown below.
* ⟨a⟩ = /a/  
* ⟨e⟩ = /e/  
* ⟨i⟩ = /i/  
* ⟨o⟩ = /o/  
* ⟨u⟩ = /u/

@frazier2009production describes four "vowel shapes" defined as "each contrastive combination of suprasegmental features (length, pitch, and
glottalization)". Orthographically, the vowel shapes are summarized below. (Further discussion of vowel shapes is in the phonology section.)
* SHORT = \<v>
* LOW TONE = \<vv>
* HIGH TONE = \<v́v>
* GLOTTALIZED = \<v’v>

# Phonology
## Consonants
All obstruents are voiceless except for the implosive /ɓ/.

## Vowels
In terms of vowel quality, YM has a five-vowel system.

|      |   Front   |  Central  |    Back   |
|------|:---------:|:---------:|:---------:|
| High |    /i/    |           |    /u/    |
| Mid  |    /e/    |           |    /o/    |
| Low  |           |    /a/    |           ‍|

Although there are only five vowel qualities, for every vowel, "each vowel quality can occur with four contrastive sets of suprasegmental features, resulting in 20 unique possible syllable heads" (@frazier2009production).

As summarized by @frazier2009production, these are the four vowel shapes:
* SHORT: short, unmarked for tone, modal voice
* LOW TONE: long, low tone, modal voice
* HIGH TONE: long, high tone, modal voice
* GLOTTALIZED: long, high tone followed by creaky voice

@frazier2009production also states, "The GLOTTALIZED vowels are unanimously described as being produced with initial high pitch and modal voice that is interrupted by a glottal stop (i.e. [v́ʔv]), though B&VS and B et al. recognized that this glottal stop does not always have a full realization, especially in rapid speech."

Per discussions with Scott AnderBois, the rules will represent "glottalized" vowels as a long, high tone vowel followed by creaky voice rather than a vowel interrupted by a glottal stop.
