---
title: "Sunwar"
author: "Bill Mizgerd"
bibliography: suz.bib
output: html_document
---

Last Updated: 2019-08-08

# Background

**Language Family**: Sino-Tibetan / Tibeto-Burman / Himalayan / Kiranti / Western Kiranti / Sunwar

Sunwar is an exonym; the endonym for the language is spelled various ways, including Kõits, Kõinch, and Koincha.

# Phonology

## Consonants

* /ɖ/, /tʃʰ/, and aspirated voiced stops occur in Nepali loanwords. [@SuzBorchers2008, p. 24]
* /ʈ/ and /ʈʰ/ also occur almost exclusively in loanwords, but there exists a small set of native Sunwar words that feature it. [@SuzBorchers2008, pp. 34-35]
* /ɓ/ once existed in Sunwar, but has since been lost; however, it existed recently enough that contemporary speakers remember the sound change as having occurred. In different areas, the phoneme has moved to either [b] or [w]. [@SuzBorchers2008, pp. 33-34]
* There exists a retroflex consonant that only occurs as the second sound in a consonant cluster - different speakers realize it as [ɭ] or [ɽ], and perhaps also [ɖ]. Although these were probably a single phoneme in an older form of Sunwar, they have largely diverged between different areas where Sunwar is spoken; I will be following one theory proposed by @SuzBorchers2008, by treating the modern retroflex consonants as allophones of /l/ and /ɾ/ respectively. (pp. 36-38)
* /ʔ/ is only phonemic in rare cases (followed by stops in the codas of syllables with long vowels). [@SuzBorchers2008, pp. 39-40]
* @SuzRapacha2005 argues for alveolar rather than postalveolar affricates. (p. 69)

### By place of articulation

.

### By manner of articulation

Stops: /p/, /pʰ/, /b/, /t̪/, /t̪ʰ/, /d̪/, /ʈ/, /ʈʰ/, /k/, /ɡ/, /ʔ/  
Affricates: /tʃ/, /dʒ/  
Nasals: /m/, /n/, /ŋ/  
Fricatives: /s/, /ʃ/, /h/  
Flaps: /ɾ/  
Approximants: /w/, /l̪/, /ɭ/, /j/  

## Vowels

Vowels: /i/, /u/, /uː/, /e/, /o/, /a/, /aː/  
Diphthongs: /ai/, /aĩ/, /au/, /eu/, /oa/, /oi/, /oĩ/, /ui/, /uĩ/  

* @SuzRapacha2005 argues for /ə/ as a sixth vowel in Sunwar. (pp. 57, 59-60)
* All vowels, except for /uː/, nasalize contrastively [@SuzBorchers2008, p. 23]; however, @SuzBorchers2008 theorizes that this contrast may be gradually disappearing in Sunwar (pp. 27-28).
* Tone exists in Sunwar, but @SuzBorchers2008 argues that it is predictable, and states that he was unable to identify any minimal pairs that differ only in tone (pp. 28-30). Similarly, @SuzRapacha2005 remarks that tone contrasts are typically neutralized in the dialect areas he studied (p. 107). For this reason, I have chosen to omit tone in my ruleset.
* The Sunwar diphthongs may occur as sequences of vowels when they exist across morpheme boundaries. [@SuzBorchers2008, p. 31]

# Alphabet

## Consonants

क - /ka/  
ख - /kʰa/  
ग - /ɡa/  
घ - /ɡʱa/ (only in loanwords)  
ङ - /ŋa/  
च - /tʃa/  
छ - /tʃʰa/ (only in loanwords)  
ज - /dʒa/  
झ - /dʒʱa/ (only in loanwords)  
ट - /ʈa/ (rare)  
ठ - /ʈʰa/ (rare)  
ड - /ɖa/ (only in loanwords)  
ढ - /ɖʱa/ (only in loanwords)  
त - /t̪a/  
थ - /t̪ʰa/  
द - /d̪a/  
ध - /d̪ʱa/ (only in loanwords)  
न - /na/  
प - /pa/  
फ - /pʰa/  
ब - /ba/  
भ - /bʱa/ (only in loanwords)  
म - /ma/  
य - /ja/  
र - /ɾa/  
ल - /la/  
व - /wa/  
स - /sa/  
ष - /ʃa/  
श - /ʃa/  
ह - /ha/  

The glottal stop is not consistently represented in the orthography. Some authors write it by repeating the vowel of a syllable, and adding the <्> diacritic to the second instance; others represent the glottal stop with the character for /k/, and still others don't include the glottal stop at all [@SuzBorchers2008, p. 49]. Because of the relatively rare nature of /ʔ/, I have opted to proceed with the language anyway.

## Vowel Characters

अ - /a/  
आ - /aː/  
इ - /i/  
उ - /u/  
ऊ - /uː/  
ए - /e/  
ऐ - /ai/  
ओ - /o/  
औ - /au/  

## Vowel Diacritics

् - ∅
ा - /aː/  
ि - /i/  
ु - /u/  
ू - /uː/  
े - /e/  
ै - /ai/  
ो - /o/  
ौ - /au/  
ं - marks vowel nasality  

# Lenition Rules

* Some speakers spirantize /pʰ/ to [ɸ]. [@SuzBorchers2008, p. 32]
* Syllable-final /n/ and /ŋ/ are often realized weakly, and simply nasalize the preceding vowel. (ibid.)
* Word-final vowels may delete in fast speech. [@SuzRapacha2005, p. 68]

# Misc. Rules

* In fast speech, the short vowel /a/ tends to back to [ɑ], and /e/ tends to lower to [ɛ]. [@SuzBorchers2008, p. 25]
* /i/ lengthens to [iː] in some word classes. [@SuzBorchers2008, pp. 26-27]
* Word-initial /w/ may gain aspiration. [@SuzBorchers2008, p. 33]
* /ɾ/ trills to [r] before palatal or velar consonants. [@SuzBorchers2008, p. 35]
* Epenthesis of [x] occurs between /ɾ/ and /tʃ/. [@SuzBorchers2008, p. 39]
* Postvocalic /l/ velarizes to [ɫ] when followed by another /l/. [@SuzRapacha2005, p. 83]

## Syllable Structure

The syllable structure of Sunwar is (C)(C)V(V)(C)(C). Syllables must have at most one consonant, and in most cases can contain a maximum of four sounds.

# References
