---
title: "Bora"
author: "Bill Mizgerd"
bibliography: boa.bib
output: html_document
---

Last Updated: 2019-07-02

# Background

**Language Family**: Witotoan / Boran / Bora

# Phonology

## Consonants

* @BoaRoe2014 describes /x/ as a phoneme in Bora (p. 8); @BoaThiesen2012 lists /x ~ h/ in free variation (p. 33), and while he prefers /h/ as the underlying phoneme, the majority of the evidence seems to point to /x/.
* Different authors have interpreted the flap differently: opinions have ranged from /r/ to /ɾ/ to /ɽ/ [@BoaRoe2014, p. 9]. I have opted to prefer /ɾ/ in my ruleset.
* Consonants followed by /j/ palatalize, and the /j/ deletes. @BoaThiesen2012 does not make a firm decision on whether these palatalized consonants are contrastive (p. 33); @BoaRoe2014 argues against it (pp. 8-9), and I follow her lead in my ruleset.

### By place of articulation

Bilabial: /p/, /pʰ/, /m/, /β/  
Alveolar: /t/, /tʰ/, /ts/, /tsʰ/, /n/, /ɾ/  
Postalveolar: /tʃ/, /tʃʰ/  
Palatal: /j/  
Velar: /k/, /kʰ/, /kp/, /x/  
Glottal: /ʔ/  

### By manner of articulation

Stops: /p/, /pʰ/, /t/, /tʰ/, /k/, /kʰ/, /kp/, /ʔ/  
Affricates: /ts/, /tsʰ/, /tʃ/, /tʃʰ/  
Nasals: /m/, /n/  
Fricatives: /β/, /x/  
Flaps: /ɾ/  
Semivowels: /j/  

## Vowels

Vowels: /i/, /ɨ/, /ɯ/, /ɛ/, /o/, /a/  

Bora has two contrastive tones, high and low. [@BoaThiesen2012, p. 27]

Vowel length is contrastive in Bora.

# Alphabet

a - /a/  
b - /p/  
c - /kʰ/  
ch - /tʃʰ/  
d - /t/  
ds - /ts/  
e - /ɛ/  
g - /k/  
h - /ʔ/  
i - /i/  
ɨ - /ɨ/  
j - /x/  
k - /kʰ/  
ll - /tʃ/  
m - /m/  
n - /n/  
ñ - /ɲ/  
o - /o/  
p - /pʰ/  
r - /ɾ/  
t - /tʰ/  
ts - /tsʰ/  
u - /ɯ/  
v - /β/  
w - /kp/  
y - /j/  

* High tone is marked with an acute accent on the vowel; low tone is unmarked. [@BoaThiesen2012, p. 27]
* Long vowels are written by repeating the vowel character. (ibid.)

# Lenition Rules

* Postconsonantal /j/ tends to delete, and instead just palatalizes the previous consonant. [@BoaThiesen2012, p. 27]
* In syllable codas, /x/ is simply produced as a preaspiration of the following consonant (written by Thiesen as [ˣ]). [@BoaThiesen2012, p. 40]
* Syllable-final /ʔ/ is produced as simply a glottalization of the vowel (written as [ˀ]). [@BoaThiesen2012, p. 28]
* /kp/ becomes [kʷ] in fast speech, particularly among younger speakers. [@BoaRoe2014, p. 9]

# Misc. Rules

* /i/ lowers in /x/-final syllables, and centralizes to [ɨ] when /ɨ/ is present in the following syllable. [@BoaThiesen2012, p. 30]
* /ɛ/ lowers to [æ] before syllables that contain /i/. [@BoaThiesen2012, p. 31]
* Epenthesis of [ʔ] occurs at the beginning of vowel-initial phrases, and the end of vowel-final phrases. [@BoaThiesen2012, p. 36]
* In Bora, two low-tone vowels cannot occur consecutively unless they are word-final. [@BoaThiesen2012, p. 69]

## Syllable Structure

Bora syllables mostly take the form of (C)V, although /x/ and /ʔ/ can appear as syllable codas. [@BoaRoe2014, p. 9]

# References
